# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019 Lars Povlsen <lars.povlsen@microchip.com>
#

obj-y	= cpu.o ddr.o
obj-$(CONFIG_FIREANT_SYMREG) += fa_symregs.o symreg.o
obj-$(CONFIG_SPI) += spi.o
