/*
 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/

#ifndef _MSCC_FA_REGS_DEVCPU_GCB_H_
#define _MSCC_FA_REGS_DEVCPU_GCB_H_

#include "mscc_fa_regs_common.h"

#define MSCC_DEVCPU_GCB_CHIP_ID              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x0)
#define  MSCC_F_DEVCPU_GCB_CHIP_ID_REV_ID(x)            (GENMASK(31,28) & ((x) << 28))
#define  MSCC_M_DEVCPU_GCB_CHIP_ID_REV_ID               GENMASK(31,28)
#define  MSCC_X_DEVCPU_GCB_CHIP_ID_REV_ID(x)            (((x) >> 28) & GENMASK(3,0))
#define  MSCC_F_DEVCPU_GCB_CHIP_ID_PART_ID(x)           (GENMASK(27,12) & ((x) << 12))
#define  MSCC_M_DEVCPU_GCB_CHIP_ID_PART_ID              GENMASK(27,12)
#define  MSCC_X_DEVCPU_GCB_CHIP_ID_PART_ID(x)           (((x) >> 12) & GENMASK(15,0))
#define  MSCC_F_DEVCPU_GCB_CHIP_ID_MFG_ID(x)            (GENMASK(11,1) & ((x) << 1))
#define  MSCC_M_DEVCPU_GCB_CHIP_ID_MFG_ID               GENMASK(11,1)
#define  MSCC_X_DEVCPU_GCB_CHIP_ID_MFG_ID(x)            (((x) >> 1) & GENMASK(10,0))
#define  MSCC_F_DEVCPU_GCB_CHIP_ID_ONE(x)               ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_CHIP_ID_ONE                  BIT(0)
#define  MSCC_X_DEVCPU_GCB_CHIP_ID_ONE(x)               ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_GPR                  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1)
#define  MSCC_F_DEVCPU_GCB_GPR_GPR(x)                   (x)
#define  MSCC_M_DEVCPU_GCB_GPR_GPR                      0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPR_GPR(x)                   (x)

#define MSCC_DEVCPU_GCB_SOFT_RST             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x2)
#define  MSCC_F_DEVCPU_GCB_SOFT_RST_SOFT_NON_CFG_RST(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_SOFT_RST_SOFT_NON_CFG_RST     BIT(2)
#define  MSCC_X_DEVCPU_GCB_SOFT_RST_SOFT_NON_CFG_RST(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SOFT_RST_SOFT_SWC_RST(x)     ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_SOFT_RST_SOFT_SWC_RST        BIT(1)
#define  MSCC_X_DEVCPU_GCB_SOFT_RST_SOFT_SWC_RST(x)     ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SOFT_RST_SOFT_CHIP_RST(x)    ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_SOFT_RST_SOFT_CHIP_RST       BIT(0)
#define  MSCC_X_DEVCPU_GCB_SOFT_RST_SOFT_CHIP_RST(x)    ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_HW_CFG               MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x3)
#define  MSCC_F_DEVCPU_GCB_HW_CFG_DFT_STAT_ENA(x)       ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_HW_CFG_DFT_STAT_ENA          BIT(1)
#define  MSCC_X_DEVCPU_GCB_HW_CFG_DFT_STAT_ENA(x)       ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_HW_CFG_DFT_CLK_MON_ENA(x)    ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_HW_CFG_DFT_CLK_MON_ENA       BIT(0)
#define  MSCC_X_DEVCPU_GCB_HW_CFG_DFT_CLK_MON_ENA(x)    ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_HW_STAT              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x4)
#define  MSCC_F_DEVCPU_GCB_HW_STAT_PLL0_CONF(x)         (GENMASK(3,1) & ((x) << 1))
#define  MSCC_M_DEVCPU_GCB_HW_STAT_PLL0_CONF            GENMASK(3,1)
#define  MSCC_X_DEVCPU_GCB_HW_STAT_PLL0_CONF(x)         (((x) >> 1) & GENMASK(2,0))
#define  MSCC_F_DEVCPU_GCB_HW_STAT_PLL0_RSVD(x)         ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_HW_STAT_PLL0_RSVD            BIT(0)
#define  MSCC_X_DEVCPU_GCB_HW_STAT_PLL0_RSVD(x)         ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_HW_SGPIO_SD_CFG      MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x5)
#define  MSCC_F_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_HIGH_ENA(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_HIGH_ENA     BIT(1)
#define  MSCC_X_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_HIGH_ENA(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_MAP_SEL(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_MAP_SEL     BIT(0)
#define  MSCC_X_DEVCPU_GCB_HW_SGPIO_SD_CFG_SD_MAP_SEL(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_HW_SGPIO_TO_SD_MAP_CFG(ri)  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6 + (ri))
#define  MSCC_F_DEVCPU_GCB_HW_SGPIO_TO_SD_MAP_CFG_SGPIO_TO_SD_SEL(x)  (GENMASK(8,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_HW_SGPIO_TO_SD_MAP_CFG_SGPIO_TO_SD_SEL     GENMASK(8,0)
#define  MSCC_X_DEVCPU_GCB_HW_SGPIO_TO_SD_MAP_CFG_SGPIO_TO_SD_SEL(x)  (((x) >> 0) & GENMASK(8,0))

#define MSCC_DEVCPU_GCB_HW_SGPIO_TO_SERDES_SD_MAP_CFG(ri)  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x47 + (ri))
#define  MSCC_F_DEVCPU_GCB_HW_SGPIO_TO_SERDES_SD_MAP_CFG_SGPIO_TO_SERDES_SD_SEL(x)  (GENMASK(8,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_HW_SGPIO_TO_SERDES_SD_MAP_CFG_SGPIO_TO_SERDES_SD_SEL     GENMASK(8,0)
#define  MSCC_X_DEVCPU_GCB_HW_SGPIO_TO_SERDES_SD_MAP_CFG_SGPIO_TO_SERDES_SD_SEL(x)  (((x) >> 0) & GENMASK(8,0))

#define MSCC_DEVCPU_GCB_FEA_STAT             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x68)
#define  MSCC_F_DEVCPU_GCB_FEA_STAT_FEA_STAT(x)         (x)
#define  MSCC_M_DEVCPU_GCB_FEA_STAT_FEA_STAT            0xffffffff
#define  MSCC_X_DEVCPU_GCB_FEA_STAT_FEA_STAT(x)         (x)

#define MSCC_DEVCPU_GCB_FEA_DIS              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x69)
#define  MSCC_F_DEVCPU_GCB_FEA_DIS_FEA_DIS(x)           (x)
#define  MSCC_M_DEVCPU_GCB_FEA_DIS_FEA_DIS              0xffffffff
#define  MSCC_X_DEVCPU_GCB_FEA_DIS_FEA_DIS(x)           (x)

#define MSCC_DEVCPU_GCB_IF_CTRL              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6a)
#define  MSCC_F_DEVCPU_GCB_IF_CTRL_IF_CTRL(x)           (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_IF_CTRL_IF_CTRL              GENMASK(3,0)
#define  MSCC_X_DEVCPU_GCB_IF_CTRL_IF_CTRL(x)           (((x) >> 0) & GENMASK(3,0))

#define MSCC_DEVCPU_GCB_IF_CFGSTAT           MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6b)
#define  MSCC_F_DEVCPU_GCB_IF_CFGSTAT_IF_STAT(x)        ((x) ? BIT(16) : 0)
#define  MSCC_M_DEVCPU_GCB_IF_CFGSTAT_IF_STAT           BIT(16)
#define  MSCC_X_DEVCPU_GCB_IF_CFGSTAT_IF_STAT(x)        ((x) & BIT(16) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_IF_CFGSTAT_IF_CFG(x)         (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_IF_CFGSTAT_IF_CFG            GENMASK(3,0)
#define  MSCC_X_DEVCPU_GCB_IF_CFGSTAT_IF_CFG(x)         (((x) >> 0) & GENMASK(3,0))

#define MSCC_DEVCPU_GCB_SPI_MASTER_SS0_MASK  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6c)
#define  MSCC_F_DEVCPU_GCB_SPI_MASTER_SS0_MASK_SPI_SS0_MASK(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SPI_MASTER_SS0_MASK_SPI_SS0_MASK     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_SPI_MASTER_SS0_MASK_SPI_SS0_MASK(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_SPI_MASTER_SS1_MASK  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6d)
#define  MSCC_F_DEVCPU_GCB_SPI_MASTER_SS1_MASK_SPI_SS1_MASK(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SPI_MASTER_SS1_MASK_SPI_SS1_MASK     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_SPI_MASTER_SS1_MASK_SPI_SS1_MASK(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_SPI_MASTER_SS2_MASK  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6e)
#define  MSCC_F_DEVCPU_GCB_SPI_MASTER_SS2_MASK_SPI_SS2_MASK(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SPI_MASTER_SS2_MASK_SPI_SS2_MASK     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_SPI_MASTER_SS2_MASK_SPI_SS2_MASK(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_SPI_MASTER_SS3_MASK  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x6f)
#define  MSCC_F_DEVCPU_GCB_SPI_MASTER_SS3_MASK_SPI_SS3_MASK(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SPI_MASTER_SS3_MASK_SPI_SS3_MASK     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_SPI_MASTER_SS3_MASK_SPI_SS3_MASK(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_SI_SLV_SS            MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x70)
#define  MSCC_F_DEVCPU_GCB_SI_SLV_SS_SS_SEL(x)          (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SI_SLV_SS_SS_SEL             GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_SI_SLV_SS_SS_SEL(x)          (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_SW_INTR              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x71)
#define  MSCC_F_DEVCPU_GCB_SW_INTR_SW1_INTR(x)          ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_SW_INTR_SW1_INTR             BIT(1)
#define  MSCC_X_DEVCPU_GCB_SW_INTR_SW1_INTR(x)          ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SW_INTR_SW0_INTR(x)          ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_SW_INTR_SW0_INTR             BIT(0)
#define  MSCC_X_DEVCPU_GCB_SW_INTR_SW0_INTR(x)          ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_VA_CTRL              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x72)
#define  MSCC_F_DEVCPU_GCB_VA_CTRL_VA_SIZE(x)           (GENMASK(5,4) & ((x) << 4))
#define  MSCC_M_DEVCPU_GCB_VA_CTRL_VA_SIZE              GENMASK(5,4)
#define  MSCC_X_DEVCPU_GCB_VA_CTRL_VA_SIZE(x)           (((x) >> 4) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_VA_CTRL_VA_ERR(x)            (GENMASK(3,2) & ((x) << 2))
#define  MSCC_M_DEVCPU_GCB_VA_CTRL_VA_ERR               GENMASK(3,2)
#define  MSCC_X_DEVCPU_GCB_VA_CTRL_VA_ERR(x)            (((x) >> 2) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_VA_CTRL_VA_BUSY_RD(x)        ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_VA_CTRL_VA_BUSY_RD           BIT(1)
#define  MSCC_X_DEVCPU_GCB_VA_CTRL_VA_BUSY_RD(x)        ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_VA_CTRL_VA_BUSY(x)           ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_VA_CTRL_VA_BUSY              BIT(0)
#define  MSCC_X_DEVCPU_GCB_VA_CTRL_VA_BUSY(x)           ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_VA_ADDR_LSB          MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x73)
#define  MSCC_F_DEVCPU_GCB_VA_ADDR_LSB_VA_ADDR_LSB(x)   (x)
#define  MSCC_M_DEVCPU_GCB_VA_ADDR_LSB_VA_ADDR_LSB      0xffffffff
#define  MSCC_X_DEVCPU_GCB_VA_ADDR_LSB_VA_ADDR_LSB(x)   (x)

#define MSCC_DEVCPU_GCB_VA_ADDR_MSB          MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x74)
#define  MSCC_F_DEVCPU_GCB_VA_ADDR_MSB_VA_ADDR_MSB(x)   (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_VA_ADDR_MSB_VA_ADDR_MSB      GENMASK(3,0)
#define  MSCC_X_DEVCPU_GCB_VA_ADDR_MSB_VA_ADDR_MSB(x)   (((x) >> 0) & GENMASK(3,0))

#define MSCC_DEVCPU_GCB_VA_DATA              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x75)
#define  MSCC_F_DEVCPU_GCB_VA_DATA_VA_DATA(x)           (x)
#define  MSCC_M_DEVCPU_GCB_VA_DATA_VA_DATA              0xffffffff
#define  MSCC_X_DEVCPU_GCB_VA_DATA_VA_DATA(x)           (x)

#define MSCC_DEVCPU_GCB_VA_DATA_INCR         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x76)
#define  MSCC_F_DEVCPU_GCB_VA_DATA_INCR_VA_DATA_INCR(x)  (x)
#define  MSCC_M_DEVCPU_GCB_VA_DATA_INCR_VA_DATA_INCR     0xffffffff
#define  MSCC_X_DEVCPU_GCB_VA_DATA_INCR_VA_DATA_INCR(x)  (x)

#define MSCC_DEVCPU_GCB_VA_DATA_INERT        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x77)
#define  MSCC_F_DEVCPU_GCB_VA_DATA_INERT_VA_DATA_INERT(x)  (x)
#define  MSCC_M_DEVCPU_GCB_VA_DATA_INERT_VA_DATA_INERT     0xffffffff
#define  MSCC_X_DEVCPU_GCB_VA_DATA_INERT_VA_DATA_INERT(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT_SET         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x78)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT_SET_G_OUT_SET(x)    (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT_SET_G_OUT_SET       0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT_SET_G_OUT_SET(x)    (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT_SET1        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x79)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT_SET1_G_OUT_SET1(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT_SET1_G_OUT_SET1     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT_SET1_G_OUT_SET1(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT_CLR         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7a)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT_CLR_G_OUT_CLR(x)    (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT_CLR_G_OUT_CLR       0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT_CLR_G_OUT_CLR(x)    (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT_CLR1        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7b)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT_CLR1_G_OUT_CLR1(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT_CLR1_G_OUT_CLR1     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT_CLR1_G_OUT_CLR1(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7c)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT_G_OUT(x)            (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT_G_OUT               0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT_G_OUT(x)            (x)

#define MSCC_DEVCPU_GCB_GPIO_OUT1            MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7d)
#define  MSCC_F_DEVCPU_GCB_GPIO_OUT1_G_OUT1(x)          (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OUT1_G_OUT1             0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OUT1_G_OUT1(x)          (x)

#define MSCC_DEVCPU_GCB_GPIO_IN              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7e)
#define  MSCC_F_DEVCPU_GCB_GPIO_IN_G_IN(x)              (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_IN_G_IN                 0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_IN_G_IN(x)              (x)

#define MSCC_DEVCPU_GCB_GPIO_IN1             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x7f)
#define  MSCC_F_DEVCPU_GCB_GPIO_IN1_G_IN1(x)            (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_IN1_G_IN1               0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_IN1_G_IN1(x)            (x)

#define MSCC_DEVCPU_GCB_GPIO_OE              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x80)
#define  MSCC_F_DEVCPU_GCB_GPIO_OE_G_OE(x)              (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OE_G_OE                 0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OE_G_OE(x)              (x)

#define MSCC_DEVCPU_GCB_GPIO_OE1             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x81)
#define  MSCC_F_DEVCPU_GCB_GPIO_OE1_G_OE1(x)            (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_OE1_G_OE1               0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_OE1_G_OE1(x)            (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR            MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x82)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR_G_INTR(x)          (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR_G_INTR             0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR_G_INTR(x)          (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR1           MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x83)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR1_G_INTR1(x)        (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR1_G_INTR1           0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR1_G_INTR1(x)        (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR_ENA        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x84)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR_ENA_G_INTR_ENA(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR_ENA_G_INTR_ENA     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR_ENA_G_INTR_ENA(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR_ENA1       MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x85)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR_ENA1_G_INTR_ENA1(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR_ENA1_G_INTR_ENA1     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR_ENA1_G_INTR_ENA1(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR_IDENT      MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x86)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR_IDENT_G_INTR_IDENT(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR_IDENT_G_INTR_IDENT     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR_IDENT_G_INTR_IDENT(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_INTR_IDENT1     MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x87)
#define  MSCC_F_DEVCPU_GCB_GPIO_INTR_IDENT1_G_INTR_IDENT1(x)  (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_INTR_IDENT1_G_INTR_IDENT1     0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_INTR_IDENT1_G_INTR_IDENT1(x)  (x)

#define MSCC_DEVCPU_GCB_GPIO_ALT(ri)         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x88 + (ri))
#define  MSCC_F_DEVCPU_GCB_GPIO_ALT_G_ALT(x)            (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_ALT_G_ALT               0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_ALT_G_ALT(x)            (x)

#define MSCC_DEVCPU_GCB_GPIO_ALT1(ri)        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x8a + (ri))
#define  MSCC_F_DEVCPU_GCB_GPIO_ALT1_G_ALT1(x)          (x)
#define  MSCC_M_DEVCPU_GCB_GPIO_ALT1_G_ALT1             0xffffffff
#define  MSCC_X_DEVCPU_GCB_GPIO_ALT1_G_ALT1(x)          (x)

#define MSCC_DEVCPU_GCB_GPIO_SD_MAP(ri)      MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x8c + (ri))
#define  MSCC_F_DEVCPU_GCB_GPIO_SD_MAP_G_SD_MAP(x)      (GENMASK(6,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_GPIO_SD_MAP_G_SD_MAP         GENMASK(6,0)
#define  MSCC_X_DEVCPU_GCB_GPIO_SD_MAP_G_SD_MAP(x)      (((x) >> 0) & GENMASK(6,0))

#define MSCC_DEVCPU_GCB_MII_STATUS(gi)       MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,0)
#define  MSCC_F_DEVCPU_GCB_MII_STATUS_MIIM_STAT_BUSY(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_STATUS_MIIM_STAT_BUSY     BIT(3)
#define  MSCC_X_DEVCPU_GCB_MII_STATUS_MIIM_STAT_BUSY(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_STATUS_MIIM_STAT_OPR_PEND(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_STATUS_MIIM_STAT_OPR_PEND     BIT(2)
#define  MSCC_X_DEVCPU_GCB_MII_STATUS_MIIM_STAT_OPR_PEND(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_RD(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_RD     BIT(1)
#define  MSCC_X_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_RD(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_WR(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_WR     BIT(0)
#define  MSCC_X_DEVCPU_GCB_MII_STATUS_MIIM_STAT_PENDING_WR(x)  ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_STATUS_MIIM_SCAN_COMPLETE(x)  ((x) ? BIT(4) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_STATUS_MIIM_SCAN_COMPLETE     BIT(4)
#define  MSCC_X_DEVCPU_GCB_MII_STATUS_MIIM_SCAN_COMPLETE(x)  ((x) & BIT(4) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MII_CFG_7226(gi)     MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,1)
#define  MSCC_F_DEVCPU_GCB_MII_CFG_7226_MIIM_7226_CFG_FIELD(x)  ((x) ? BIT(9) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CFG_7226_MIIM_7226_CFG_FIELD     BIT(9)
#define  MSCC_X_DEVCPU_GCB_MII_CFG_7226_MIIM_7226_CFG_FIELD(x)  ((x) & BIT(9) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MII_CMD(gi)          MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,2)
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_VLD(x)      ((x) ? BIT(31) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_VLD         BIT(31)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_VLD(x)      ((x) & BIT(31) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_PHYAD(x)    (GENMASK(29,25) & ((x) << 25))
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_PHYAD       GENMASK(29,25)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_PHYAD(x)    (((x) >> 25) & GENMASK(4,0))
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_REGAD(x)    (GENMASK(24,20) & ((x) << 20))
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_REGAD       GENMASK(24,20)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_REGAD(x)    (((x) >> 20) & GENMASK(4,0))
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_WRDATA(x)   (GENMASK(19,4) & ((x) << 4))
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_WRDATA      GENMASK(19,4)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_WRDATA(x)   (((x) >> 4) & GENMASK(15,0))
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_SINGLE_SCAN(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_SINGLE_SCAN     BIT(3)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_SINGLE_SCAN(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_OPR_FIELD(x)  (GENMASK(2,1) & ((x) << 1))
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_OPR_FIELD     GENMASK(2,1)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_OPR_FIELD(x)  (((x) >> 1) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_MII_CMD_MIIM_CMD_SCAN(x)     ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CMD_MIIM_CMD_SCAN        BIT(0)
#define  MSCC_X_DEVCPU_GCB_MII_CMD_MIIM_CMD_SCAN(x)     ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MII_DATA(gi)         MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,3)
#define  MSCC_F_DEVCPU_GCB_MII_DATA_MIIM_DATA_SUCCESS(x)  (GENMASK(17,16) & ((x) << 16))
#define  MSCC_M_DEVCPU_GCB_MII_DATA_MIIM_DATA_SUCCESS     GENMASK(17,16)
#define  MSCC_X_DEVCPU_GCB_MII_DATA_MIIM_DATA_SUCCESS(x)  (((x) >> 16) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_MII_DATA_MIIM_DATA_RDDATA(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MII_DATA_MIIM_DATA_RDDATA     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_MII_DATA_MIIM_DATA_RDDATA(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_MII_CFG(gi)          MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,4)
#define  MSCC_F_DEVCPU_GCB_MII_CFG_DEADLOCK_FIX_DIS(x)  ((x) ? BIT(11) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CFG_DEADLOCK_FIX_DIS     BIT(11)
#define  MSCC_X_DEVCPU_GCB_MII_CFG_DEADLOCK_FIX_DIS(x)  ((x) & BIT(11) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MII_CFG_MIIM_CFG_PRESCALE(x)  (GENMASK(7,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MII_CFG_MIIM_CFG_PRESCALE     GENMASK(7,0)
#define  MSCC_X_DEVCPU_GCB_MII_CFG_MIIM_CFG_PRESCALE(x)  (((x) >> 0) & GENMASK(7,0))
#define  MSCC_F_DEVCPU_GCB_MII_CFG_MIIM_ST_CFG_FIELD(x)  (GENMASK(10,9) & ((x) << 9))
#define  MSCC_M_DEVCPU_GCB_MII_CFG_MIIM_ST_CFG_FIELD     GENMASK(10,9)
#define  MSCC_X_DEVCPU_GCB_MII_CFG_MIIM_ST_CFG_FIELD(x)  (((x) >> 9) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_MII_CFG_MIIM_CFG_DBG(x)      ((x) ? BIT(8) : 0)
#define  MSCC_M_DEVCPU_GCB_MII_CFG_MIIM_CFG_DBG         BIT(8)
#define  MSCC_X_DEVCPU_GCB_MII_CFG_MIIM_CFG_DBG(x)      ((x) & BIT(8) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MII_SCAN_0(gi)       MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,5)
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADHI(x)  (GENMASK(9,5) & ((x) << 5))
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADHI     GENMASK(9,5)
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADHI(x)  (((x) >> 5) & GENMASK(4,0))
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADLO(x)  (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADLO     GENMASK(4,0)
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_0_MIIM_SCAN_PHYADLO(x)  (((x) >> 0) & GENMASK(4,0))

#define MSCC_DEVCPU_GCB_MII_SCAN_1(gi)       MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,6)
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_MASK(x)  (GENMASK(31,16) & ((x) << 16))
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_MASK     GENMASK(31,16)
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_MASK(x)  (((x) >> 16) & GENMASK(15,0))
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_EXPECT(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_EXPECT     GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_1_MIIM_SCAN_EXPECT(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_MII_SCAN_LAST_RSLTS(gi)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,7)
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_MIIM_LAST_RSLT(x)  (x)
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_MIIM_LAST_RSLT     0xffffffff
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_MIIM_LAST_RSLT(x)  (x)

#define MSCC_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_VLD(gi)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xac,gi,9,0,8)
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_VLD_MIIM_LAST_RSLT_VLD(x)  (x)
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_VLD_MIIM_LAST_RSLT_VLD     0xffffffff
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_LAST_RSLTS_VLD_MIIM_LAST_RSLT_VLD(x)  (x)

#define MSCC_DEVCPU_GCB_MII_SCAN_RSLTS_STICKY(ri)  MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0xd0 + (ri))
#define  MSCC_F_DEVCPU_GCB_MII_SCAN_RSLTS_STICKY_MIIM_SCAN_RSLTS_STICKY(x)  (x)
#define  MSCC_M_DEVCPU_GCB_MII_SCAN_RSLTS_STICKY_MIIM_SCAN_RSLTS_STICKY     0xffffffff
#define  MSCC_X_DEVCPU_GCB_MII_SCAN_RSLTS_STICKY_MIIM_SCAN_RSLTS_STICKY(x)  (x)

#define MSCC_DEVCPU_GCB_ROSC_CFG(ri)         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0xd4 + (ri))
#define  MSCC_F_DEVCPU_GCB_ROSC_CFG_ROSC_MODE(x)        (GENMASK(2,1) & ((x) << 1))
#define  MSCC_M_DEVCPU_GCB_ROSC_CFG_ROSC_MODE           GENMASK(2,1)
#define  MSCC_X_DEVCPU_GCB_ROSC_CFG_ROSC_MODE(x)        (((x) >> 1) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_ROSC_CFG_ROSC_ENA(x)         ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_ROSC_CFG_ROSC_ENA            BIT(0)
#define  MSCC_X_DEVCPU_GCB_ROSC_CFG_ROSC_ENA(x)         ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_ROSC_MEASURE_CFG     MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0xd9)
#define  MSCC_F_DEVCPU_GCB_ROSC_MEASURE_CFG_TIME_BASE(x)  (GENMASK(25,13) & ((x) << 13))
#define  MSCC_M_DEVCPU_GCB_ROSC_MEASURE_CFG_TIME_BASE     GENMASK(25,13)
#define  MSCC_X_DEVCPU_GCB_ROSC_MEASURE_CFG_TIME_BASE(x)  (((x) >> 13) & GENMASK(12,0))
#define  MSCC_F_DEVCPU_GCB_ROSC_MEASURE_CFG_MEASURE_TIME(x)  (GENMASK(12,5) & ((x) << 5))
#define  MSCC_M_DEVCPU_GCB_ROSC_MEASURE_CFG_MEASURE_TIME     GENMASK(12,5)
#define  MSCC_X_DEVCPU_GCB_ROSC_MEASURE_CFG_MEASURE_TIME(x)  (((x) >> 5) & GENMASK(7,0))
#define  MSCC_F_DEVCPU_GCB_ROSC_MEASURE_CFG_START(x)    ((x) ? BIT(4) : 0)
#define  MSCC_M_DEVCPU_GCB_ROSC_MEASURE_CFG_START       BIT(4)
#define  MSCC_X_DEVCPU_GCB_ROSC_MEASURE_CFG_START(x)    ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_ROSC_MEASURE_CFG_ROSC_SEL(x)  (GENMASK(2,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_ROSC_MEASURE_CFG_ROSC_SEL     GENMASK(2,0)
#define  MSCC_X_DEVCPU_GCB_ROSC_MEASURE_CFG_ROSC_SEL(x)  (((x) >> 0) & GENMASK(2,0))

#define MSCC_DEVCPU_GCB_ROSC_FREQ_CNT        MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0xda)
#define  MSCC_F_DEVCPU_GCB_ROSC_FREQ_CNT_FREQ_CNT(x)    (GENMASK(16,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_ROSC_FREQ_CNT_FREQ_CNT       GENMASK(16,0)
#define  MSCC_X_DEVCPU_GCB_ROSC_FREQ_CNT_FREQ_CNT(x)    (((x) >> 0) & GENMASK(16,0))

#define MSCC_DEVCPU_GCB_SIO_INPUT_DATA(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,0)
#define  MSCC_F_DEVCPU_GCB_SIO_INPUT_DATA_SIO_INPUT_DATA(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INPUT_DATA_SIO_INPUT_DATA     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INPUT_DATA_SIO_INPUT_DATA(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_CFG(gi)          MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,0,4)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_PWM_WINDOW(x)    (GENMASK(27,20) & ((x) << 20))
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_PWM_WINDOW       GENMASK(27,20)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_PWM_WINDOW(x)    (((x) >> 20) & GENMASK(7,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_REDUCED_GAP(x)   ((x) ? BIT(19) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_REDUCED_GAP      BIT(19)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_REDUCED_GAP(x)   ((x) & BIT(19) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_BMODE_1(x)       (GENMASK(18,17) & ((x) << 17))
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_BMODE_1          GENMASK(18,17)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_BMODE_1(x)       (((x) >> 17) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_BMODE_0(x)       (GENMASK(16,15) & ((x) << 15))
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_BMODE_0          GENMASK(16,15)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_BMODE_0(x)       (((x) >> 15) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_BLINK_RESET(x)   ((x) ? BIT(14) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_BLINK_RESET      BIT(14)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_BLINK_RESET(x)   ((x) & BIT(14) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP_DIS(x)  ((x) ? BIT(13) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP_DIS     BIT(13)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP_DIS(x)  ((x) & BIT(13) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP(x)     (GENMASK(12,8) & ((x) << 8))
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP        GENMASK(12,8)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_BURST_GAP(x)     (((x) >> 8) & GENMASK(4,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_SINGLE_SHOT(x)   ((x) ? BIT(7) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_SINGLE_SHOT      BIT(7)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_SINGLE_SHOT(x)   ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_AUTO_REPEAT(x)   ((x) ? BIT(6) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_AUTO_REPEAT      BIT(6)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_AUTO_REPEAT(x)   ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_LD_POLARITY(x)   ((x) ? BIT(5) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_LD_POLARITY      BIT(5)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_LD_POLARITY(x)   ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_PORT_WIDTH(x)    (GENMASK(4,3) & ((x) << 3))
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_PORT_WIDTH       GENMASK(4,3)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_PORT_WIDTH(x)    (((x) >> 3) & GENMASK(1,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_OUTPUT(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_OUTPUT     BIT(2)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_OUTPUT(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_INPUT(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_INPUT     BIT(1)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_REVERSE_INPUT(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_SIO_CFG_SIO_MASTER_INTR_ENA(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_SIO_CFG_SIO_MASTER_INTR_ENA     BIT(0)
#define  MSCC_X_DEVCPU_GCB_SIO_CFG_SIO_MASTER_INTR_ENA(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_SIO_CLOCK(gi)        MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,0,5)
#define  MSCC_F_DEVCPU_GCB_SIO_CLOCK_SIO_CLK_FREQ(x)    (GENMASK(19,8) & ((x) << 8))
#define  MSCC_M_DEVCPU_GCB_SIO_CLOCK_SIO_CLK_FREQ       GENMASK(19,8)
#define  MSCC_X_DEVCPU_GCB_SIO_CLOCK_SIO_CLK_FREQ(x)    (((x) >> 8) & GENMASK(11,0))
#define  MSCC_F_DEVCPU_GCB_SIO_CLOCK_SYS_CLK_PERIOD(x)  (GENMASK(7,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SIO_CLOCK_SYS_CLK_PERIOD     GENMASK(7,0)
#define  MSCC_X_DEVCPU_GCB_SIO_CLOCK_SYS_CLK_PERIOD(x)  (((x) >> 0) & GENMASK(7,0))

#define MSCC_DEVCPU_GCB_SIO_PORT_CFG(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,6)
#define  MSCC_F_DEVCPU_GCB_SIO_PORT_CFG_BIT_SOURCE(x)   (GENMASK(23,12) & ((x) << 12))
#define  MSCC_M_DEVCPU_GCB_SIO_PORT_CFG_BIT_SOURCE      GENMASK(23,12)
#define  MSCC_X_DEVCPU_GCB_SIO_PORT_CFG_BIT_SOURCE(x)   (((x) >> 12) & GENMASK(11,0))
#define  MSCC_F_DEVCPU_GCB_SIO_PORT_CFG_PWM_SOURCE(x)   (GENMASK(11,4) & ((x) << 4))
#define  MSCC_M_DEVCPU_GCB_SIO_PORT_CFG_PWM_SOURCE      GENMASK(11,4)
#define  MSCC_X_DEVCPU_GCB_SIO_PORT_CFG_PWM_SOURCE(x)   (((x) >> 4) & GENMASK(7,0))
#define  MSCC_F_DEVCPU_GCB_SIO_PORT_CFG_BIT_POLARITY(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SIO_PORT_CFG_BIT_POLARITY     GENMASK(3,0)
#define  MSCC_X_DEVCPU_GCB_SIO_PORT_CFG_BIT_POLARITY(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_DEVCPU_GCB_SIO_PORT_ENA(gi)     MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,0,38)
#define  MSCC_F_DEVCPU_GCB_SIO_PORT_ENA_SIO_PORT_ENA(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_PORT_ENA_SIO_PORT_ENA     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_PORT_ENA_SIO_PORT_ENA(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_PWM_CFG(gi,ri)   MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,39)
#define  MSCC_F_DEVCPU_GCB_SIO_PWM_CFG_PWM_DUTY_CYCLE(x)  (GENMASK(7,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_SIO_PWM_CFG_PWM_DUTY_CYCLE     GENMASK(7,0)
#define  MSCC_X_DEVCPU_GCB_SIO_PWM_CFG_PWM_DUTY_CYCLE(x)  (((x) >> 0) & GENMASK(7,0))

#define MSCC_DEVCPU_GCB_SIO_INTR_POL(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,42)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_POL_SIO_INTR_POL(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_POL_SIO_INTR_POL     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_POL_SIO_INTR_POL(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_INTR_RAW(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,46)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_RAW_SIO_INTR_RAW(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_RAW_SIO_INTR_RAW     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_RAW_SIO_INTR_RAW(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_INTR_TRIGGER0(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,50)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_TRIGGER0_SIO_INTR_TRIGGER0(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_TRIGGER0_SIO_INTR_TRIGGER0     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_TRIGGER0_SIO_INTR_TRIGGER0(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_INTR_TRIGGER1(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,54)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_TRIGGER1_SIO_INTR_TRIGGER1(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_TRIGGER1_SIO_INTR_TRIGGER1     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_TRIGGER1_SIO_INTR_TRIGGER1(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_INTR(gi,ri)      MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,58)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_SIO_INTR(x)         (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_SIO_INTR            0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_SIO_INTR(x)         (x)

#define MSCC_DEVCPU_GCB_SIO_INTR_ENA(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,62)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_ENA_SIO_INTR_ENA(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_ENA_SIO_INTR_ENA     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_ENA_SIO_INTR_ENA(x)  (x)

#define MSCC_DEVCPU_GCB_SIO_INTR_IDENT(gi,ri)  MSCC_IOREG_IX(MSCC_TO_DEVCPU_GCB,0xdb,gi,70,ri,66)
#define  MSCC_F_DEVCPU_GCB_SIO_INTR_IDENT_SIO_INTR_IDENT(x)  (x)
#define  MSCC_M_DEVCPU_GCB_SIO_INTR_IDENT_SIO_INTR_IDENT     0xffffffff
#define  MSCC_X_DEVCPU_GCB_SIO_INTR_IDENT_SIO_INTR_IDENT(x)  (x)

#define MSCC_DEVCPU_GCB_FAN_CFG              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1ad)
#define  MSCC_F_DEVCPU_GCB_FAN_CFG_DUTY_CYCLE(x)        (GENMASK(23,16) & ((x) << 16))
#define  MSCC_M_DEVCPU_GCB_FAN_CFG_DUTY_CYCLE           GENMASK(23,16)
#define  MSCC_X_DEVCPU_GCB_FAN_CFG_DUTY_CYCLE(x)        (((x) >> 16) & GENMASK(7,0))
#define  MSCC_F_DEVCPU_GCB_FAN_CFG_INV_POL(x)           ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_FAN_CFG_INV_POL              BIT(3)
#define  MSCC_X_DEVCPU_GCB_FAN_CFG_INV_POL(x)           ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_FAN_CFG_GATE_ENA(x)          ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_FAN_CFG_GATE_ENA             BIT(2)
#define  MSCC_X_DEVCPU_GCB_FAN_CFG_GATE_ENA(x)          ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_FAN_CFG_PWM_OPEN_COL_ENA(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_FAN_CFG_PWM_OPEN_COL_ENA     BIT(1)
#define  MSCC_X_DEVCPU_GCB_FAN_CFG_PWM_OPEN_COL_ENA(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_FAN_CFG_FAN_STAT_CFG(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_FAN_CFG_FAN_STAT_CFG         BIT(0)
#define  MSCC_X_DEVCPU_GCB_FAN_CFG_FAN_STAT_CFG(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_PWM_FREQ             MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1ae)
#define  MSCC_F_DEVCPU_GCB_PWM_FREQ_CLK_CYCLES_10US(x)  (GENMASK(29,17) & ((x) << 17))
#define  MSCC_M_DEVCPU_GCB_PWM_FREQ_CLK_CYCLES_10US     GENMASK(29,17)
#define  MSCC_X_DEVCPU_GCB_PWM_FREQ_CLK_CYCLES_10US(x)  (((x) >> 17) & GENMASK(12,0))
#define  MSCC_F_DEVCPU_GCB_PWM_FREQ_PWM_FREQ(x)         (GENMASK(16,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_PWM_FREQ_PWM_FREQ            GENMASK(16,0)
#define  MSCC_X_DEVCPU_GCB_PWM_FREQ_PWM_FREQ(x)         (((x) >> 0) & GENMASK(16,0))

#define MSCC_DEVCPU_GCB_FAN_CNT              MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1af)
#define  MSCC_F_DEVCPU_GCB_FAN_CNT_FAN_CNT(x)           (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_FAN_CNT_FAN_CNT              GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_FAN_CNT_FAN_CNT(x)           (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_MEMITGR_CTRL         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_CTRL_ACTIVATE(x)     ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_CTRL_ACTIVATE        BIT(0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_CTRL_ACTIVATE(x)     ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MEMITGR_STAT         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b1)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_INDICATION_OVF(x)  ((x) ? BIT(5) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_INDICATION_OVF     BIT(5)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_INDICATION_OVF(x)  ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_INDICATION(x)   ((x) ? BIT(4) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_INDICATION      BIT(4)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_INDICATION(x)   ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_MODE_LISTEN(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_MODE_LISTEN     BIT(3)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_MODE_LISTEN(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_MODE_DETECT(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_MODE_DETECT     BIT(2)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_MODE_DETECT(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_MODE_IDLE(x)    ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_MODE_IDLE       BIT(1)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_MODE_IDLE(x)    ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_STAT_MODE_BUSY(x)    ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_STAT_MODE_BUSY       BIT(0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_STAT_MODE_BUSY(x)    ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_MEMITGR_INFO         MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b2)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR(x)      ((x) ? BIT(31) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR         BIT(31)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR(x)      ((x) & BIT(31) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_INFO_MEM_COR(x)      ((x) ? BIT(30) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_INFO_MEM_COR         BIT(30)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_INFO_MEM_COR(x)      ((x) & BIT(30) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR_OVF(x)  ((x) ? BIT(29) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR_OVF     BIT(29)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_INFO_MEM_ERR_OVF(x)  ((x) & BIT(29) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_INFO_MEM_COR_OVF(x)  ((x) ? BIT(28) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_INFO_MEM_COR_OVF     BIT(28)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_INFO_MEM_COR_OVF(x)  ((x) & BIT(28) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_INFO_MEM_ADDR(x)     (GENMASK(27,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MEMITGR_INFO_MEM_ADDR        GENMASK(27,0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_INFO_MEM_ADDR(x)     (((x) >> 0) & GENMASK(27,0))

#define MSCC_DEVCPU_GCB_MEMITGR_IDX          MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b3)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_IDX_MEM_IDX(x)       (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MEMITGR_IDX_MEM_IDX          GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_IDX_MEM_IDX(x)       (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_MEMITGR_DIV          MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b4)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DIV_MEM_DIV(x)       (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DIV_MEM_DIV          GENMASK(15,0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DIV_MEM_DIV(x)       (((x) >> 0) & GENMASK(15,0))

#define MSCC_DEVCPU_GCB_MEMITGR_DBG          MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b5)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_MEM_DIV_SENSE(x)  ((x) ? BIT(9) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_MEM_DIV_SENSE     BIT(9)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_MEM_DIV_SENSE(x)  ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_FORCE_INTR(x)    ((x) ? BIT(8) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_FORCE_INTR       BIT(8)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_FORCE_INTR(x)    ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_SYNC_IN(x)       ((x) ? BIT(7) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_SYNC_IN          BIT(7)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_SYNC_IN(x)       ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_ENA_IN(x)        ((x) ? BIT(6) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_ENA_IN           BIT(6)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_ENA_IN(x)        ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_DATA_IN(x)       ((x) ? BIT(5) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_DATA_IN          BIT(5)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_DATA_IN(x)       ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_INTR_IN(x)       ((x) ? BIT(4) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_INTR_IN          BIT(4)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_INTR_IN(x)       ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_SYNC_OUT(x)      ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_SYNC_OUT         BIT(3)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_SYNC_OUT(x)      ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_ENA_OUT(x)       ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_ENA_OUT          BIT(2)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_ENA_OUT(x)       ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_FORCE_ENA(x)     ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_FORCE_ENA        BIT(1)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_FORCE_ENA(x)     ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_MEMITGR_DBG_DETECT_ENA(x)    ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_MEMITGR_DBG_DETECT_ENA       BIT(0)
#define  MSCC_X_DEVCPU_GCB_MEMITGR_DBG_DETECT_ENA(x)    ((x) & BIT(0) ? 1 : 0)

#define MSCC_DEVCPU_GCB_VRAP_ACCESS_STAT     MSCC_IOREG(MSCC_TO_DEVCPU_GCB,0x1b6)
#define  MSCC_F_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_RECV_STICKY(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_RECV_STICKY     BIT(3)
#define  MSCC_X_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_RECV_STICKY(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_VRAP_ACCESS_STAT_CMD_INVALID_STICKY(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_DEVCPU_GCB_VRAP_ACCESS_STAT_CMD_INVALID_STICKY     BIT(2)
#define  MSCC_X_DEVCPU_GCB_VRAP_ACCESS_STAT_CMD_INVALID_STICKY(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_INVALID_STICKY(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_INVALID_STICKY     BIT(1)
#define  MSCC_X_DEVCPU_GCB_VRAP_ACCESS_STAT_FRM_INVALID_STICKY(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_DEVCPU_GCB_VRAP_ACCESS_STAT_REPLY_ABORT_STICKY(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_DEVCPU_GCB_VRAP_ACCESS_STAT_REPLY_ABORT_STICKY     BIT(0)
#define  MSCC_X_DEVCPU_GCB_VRAP_ACCESS_STAT_REPLY_ABORT_STICKY(x)  ((x) & BIT(0) ? 1 : 0)


#endif /* _MSCC_FA_REGS_DEVCPU_GCB_H_ */
