/*
 Copyright (c) 2004-2018 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/

#ifndef _MSCC_FA_REGS_CPU_H_
#define _MSCC_FA_REGS_CPU_H_

#include "mscc_fa_regs_common.h"

#define MSCC_CPU_GPR(ri)                     MSCC_IOREG(MSCC_TO_CPU,0x0 + (ri))
#define  MSCC_F_CPU_GPR_GPR(x)                          (x)
#define  MSCC_M_CPU_GPR_GPR                             0xffffffff
#define  MSCC_X_CPU_GPR_GPR(x)                          (x)

#define MSCC_CPU_RESET                       MSCC_IOREG(MSCC_TO_CPU,0x20)
#define  MSCC_F_CPU_RESET_VCORE_RST(x)                  ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_RESET_VCORE_RST                     BIT(9)
#define  MSCC_X_CPU_RESET_VCORE_RST(x)                  ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_RESET_CPU_CORE_0_WARM_RST(x)        ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_RESET_CPU_CORE_0_WARM_RST           BIT(8)
#define  MSCC_X_CPU_RESET_CPU_CORE_0_WARM_RST(x)        ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_RESET_CPU_CORE_1_WARM_RST(x)        ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_RESET_CPU_CORE_1_WARM_RST           BIT(7)
#define  MSCC_X_CPU_RESET_CPU_CORE_1_WARM_RST(x)        ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROC_DBG_RST(x)               ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_RESET_PROC_DBG_RST                  BIT(6)
#define  MSCC_X_CPU_RESET_PROC_DBG_RST(x)               ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_RESET_CPU_L2_RST(x)                 ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_RESET_CPU_L2_RST                    BIT(5)
#define  MSCC_X_CPU_RESET_CPU_L2_RST(x)                 ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_RESET_MEM_RST(x)                    ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_RESET_MEM_RST                       BIT(4)
#define  MSCC_X_CPU_RESET_MEM_RST(x)                    ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_RESET_WDT_FORCE_RST(x)              ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_RESET_WDT_FORCE_RST                 BIT(3)
#define  MSCC_X_CPU_RESET_WDT_FORCE_RST(x)              ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_RESET_CPU_CORE_0_COLD_RST(x)        ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_RESET_CPU_CORE_0_COLD_RST           BIT(2)
#define  MSCC_X_CPU_RESET_CPU_CORE_0_COLD_RST(x)        ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_RESET_CPU_CORE_1_COLD_RST(x)        ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_RESET_CPU_CORE_1_COLD_RST           BIT(1)
#define  MSCC_X_CPU_RESET_CPU_CORE_1_COLD_RST(x)        ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_RESET_GIC_RST(x)                    ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_RESET_GIC_RST                       BIT(0)
#define  MSCC_X_CPU_RESET_GIC_RST(x)                    ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_RESET_PROT_STAT             MSCC_IOREG(MSCC_TO_CPU,0x21)
#define  MSCC_F_CPU_RESET_PROT_STAT_SYS_RST_PROT_VCORE(x)  ((x) ? BIT(10) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_SYS_RST_PROT_VCORE     BIT(10)
#define  MSCC_X_CPU_RESET_PROT_STAT_SYS_RST_PROT_VCORE(x)  ((x) & BIT(10) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_RST_PROT_AMBA(x)  ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_RST_PROT_AMBA     BIT(9)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_RST_PROT_AMBA(x)  ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_RST_PROT_WDT(x)  ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_RST_PROT_WDT     BIT(8)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_RST_PROT_WDT(x)  ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_RST_PROT_PDBG(x)  ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_RST_PROT_PDBG     BIT(7)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_RST_PROT_PDBG(x)  ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_RST_PROT_GIC(x)  ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_RST_PROT_GIC     BIT(6)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_RST_PROT_GIC(x)  ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_WDT_RST_PROT_WDT(x)  ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_WDT_RST_PROT_WDT     BIT(5)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_WDT_RST_PROT_WDT(x)  ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_VCORE_WDT_RST_STAT(x)  ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_VCORE_WDT_RST_STAT     BIT(4)
#define  MSCC_X_CPU_RESET_PROT_STAT_VCORE_WDT_RST_STAT(x)  ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_GIC_RST_STAT(x)     (GENMASK(3,2) & ((x) << 2))
#define  MSCC_M_CPU_RESET_PROT_STAT_GIC_RST_STAT        GENMASK(3,2)
#define  MSCC_X_CPU_RESET_PROT_STAT_GIC_RST_STAT(x)     (((x) >> 2) & GENMASK(1,0))
#define  MSCC_F_CPU_RESET_PROT_STAT_CPU_RST_PROT_L2(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_CPU_RST_PROT_L2     BIT(1)
#define  MSCC_X_CPU_RESET_PROT_STAT_CPU_RST_PROT_L2(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_RESET_PROT_STAT_SELF_RST_PROT_GIC(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_RESET_PROT_STAT_SELF_RST_PROT_GIC     BIT(0)
#define  MSCC_X_CPU_RESET_PROT_STAT_SELF_RST_PROT_GIC(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_GENERAL_CTRL                MSCC_IOREG(MSCC_TO_CPU,0x22)
#define  MSCC_F_CPU_GENERAL_CTRL_MSHC_CLK2CARD_DLY_CC(x)  (GENMASK(16,13) & ((x) << 13))
#define  MSCC_M_CPU_GENERAL_CTRL_MSHC_CLK2CARD_DLY_CC     GENMASK(16,13)
#define  MSCC_X_CPU_GENERAL_CTRL_MSHC_CLK2CARD_DLY_CC(x)  (((x) >> 13) & GENMASK(3,0))
#define  MSCC_F_CPU_GENERAL_CTRL_SIMC_SSP_ENA(x)        ((x) ? BIT(12) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_SIMC_SSP_ENA           BIT(12)
#define  MSCC_X_CPU_GENERAL_CTRL_SIMC_SSP_ENA(x)        ((x) & BIT(12) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_MIIM_SLV_ENA(x)     ((x) ? BIT(11) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_MIIM_SLV_ENA        BIT(11)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_MIIM_SLV_ENA(x)     ((x) & BIT(11) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_PI_SLV_DONEPOL(x)   ((x) ? BIT(10) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_PI_SLV_DONEPOL      BIT(10)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_PI_SLV_DONEPOL(x)   ((x) & BIT(10) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_PI_SLV_ENA(x)       ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_PI_SLV_ENA          BIT(9)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_PI_SLV_ENA(x)       ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_PI_MST_ENA(x)       ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_PI_MST_ENA          BIT(8)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_PI_MST_ENA(x)       ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_SI_OWNER(x)         (GENMASK(7,6) & ((x) << 6))
#define  MSCC_M_CPU_GENERAL_CTRL_IF_SI_OWNER            GENMASK(7,6)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_SI_OWNER(x)         (((x) >> 6) & GENMASK(1,0))
#define  MSCC_F_CPU_GENERAL_CTRL_IF_SI2_OWNER(x)        (GENMASK(5,4) & ((x) << 4))
#define  MSCC_M_CPU_GENERAL_CTRL_IF_SI2_OWNER           GENMASK(5,4)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_SI2_OWNER(x)        (((x) >> 4) & GENMASK(1,0))
#define  MSCC_F_CPU_GENERAL_CTRL_IF_SI_ENA(x)           ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_SI_ENA              BIT(3)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_SI_ENA(x)           ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_IF_SI2_ENA(x)          ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_IF_SI2_ENA             BIT(2)
#define  MSCC_X_CPU_GENERAL_CTRL_IF_SI2_ENA(x)          ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_BOOT_MODE_ENA(x)       ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_BOOT_MODE_ENA          BIT(1)
#define  MSCC_X_CPU_GENERAL_CTRL_BOOT_MODE_ENA(x)       ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_CTRL_VCORE_CPU_DIS(x)       ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_GENERAL_CTRL_VCORE_CPU_DIS          BIT(0)
#define  MSCC_X_CPU_GENERAL_CTRL_VCORE_CPU_DIS(x)       ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_GENERAL_STAT                MSCC_IOREG(MSCC_TO_CPU,0x23)
#define  MSCC_F_CPU_GENERAL_STAT_REG_IF_ERR(x)          (GENMASK(8,6) & ((x) << 6))
#define  MSCC_M_CPU_GENERAL_STAT_REG_IF_ERR             GENMASK(8,6)
#define  MSCC_X_CPU_GENERAL_STAT_REG_IF_ERR(x)          (((x) >> 6) & GENMASK(2,0))
#define  MSCC_F_CPU_GENERAL_STAT_AXI_INVLD_WR_STICKY(x)  ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_GENERAL_STAT_AXI_INVLD_WR_STICKY     BIT(5)
#define  MSCC_X_CPU_GENERAL_STAT_AXI_INVLD_WR_STICKY(x)  ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_STAT_AXI_INVLD_RD_STICKY(x)  ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_GENERAL_STAT_AXI_INVLD_RD_STICKY     BIT(4)
#define  MSCC_X_CPU_GENERAL_STAT_AXI_INVLD_RD_STICKY(x)  ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_GENERAL_STAT_VCORE_CFG(x)           (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_GENERAL_STAT_VCORE_CFG              GENMASK(3,0)
#define  MSCC_X_CPU_GENERAL_STAT_VCORE_CFG(x)           (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_ENDIANNESS                  MSCC_IOREG(MSCC_TO_CPU,0x24)
#define  MSCC_F_CPU_ENDIANNESS_REG_IF_BIGENDIAN(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_ENDIANNESS_REG_IF_BIGENDIAN         BIT(0)
#define  MSCC_X_CPU_ENDIANNESS_REG_IF_BIGENDIAN(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_SUBCPU_SYS_CFG              MSCC_IOREG(MSCC_TO_CPU,0x25)
#define  MSCC_F_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_DIS(x)    ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_DIS       BIT(2)
#define  MSCC_X_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_DIS(x)    ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE     BIT(1)
#define  MSCC_X_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE_PROT_AMBA(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE_PROT_AMBA     BIT(0)
#define  MSCC_X_CPU_SUBCPU_SYS_CFG_SUBCPU_SYS_RST_FORCE_PROT_AMBA(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_SHARED_INTR                 MSCC_IOREG(MSCC_TO_CPU,0x26)
#define  MSCC_F_CPU_SHARED_INTR_SHARED_INTR(x)          (GENMASK(9,0) & ((x) << 0))
#define  MSCC_M_CPU_SHARED_INTR_SHARED_INTR             GENMASK(9,0)
#define  MSCC_X_CPU_SHARED_INTR_SHARED_INTR(x)          (((x) >> 0) & GENMASK(9,0))

#define MSCC_CPU_SHARED_INTR_CLR             MSCC_IOREG(MSCC_TO_CPU,0x27)
#define  MSCC_F_CPU_SHARED_INTR_CLR_SHARED_INTR_CLR(x)  (GENMASK(9,0) & ((x) << 0))
#define  MSCC_M_CPU_SHARED_INTR_CLR_SHARED_INTR_CLR     GENMASK(9,0)
#define  MSCC_X_CPU_SHARED_INTR_CLR_SHARED_INTR_CLR(x)  (((x) >> 0) & GENMASK(9,0))

#define MSCC_CPU_SHARED_INTR_SET             MSCC_IOREG(MSCC_TO_CPU,0x28)
#define  MSCC_F_CPU_SHARED_INTR_SET_SHARED_INTR_SET(x)  (GENMASK(9,0) & ((x) << 0))
#define  MSCC_M_CPU_SHARED_INTR_SET_SHARED_INTR_SET     GENMASK(9,0)
#define  MSCC_X_CPU_SHARED_INTR_SET_SHARED_INTR_SET(x)  (((x) >> 0) & GENMASK(9,0))

#define MSCC_CPU_SS_FORCE_ENA                MSCC_IOREG(MSCC_TO_CPU,0x29)
#define  MSCC_F_CPU_SS_FORCE_ENA_SS_FORCE_ENA(x)        ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_SS_FORCE_ENA_SS_FORCE_ENA           BIT(0)
#define  MSCC_X_CPU_SS_FORCE_ENA_SS_FORCE_ENA(x)        ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_SS_FORCE                    MSCC_IOREG(MSCC_TO_CPU,0x2a)
#define  MSCC_F_CPU_SS_FORCE_SS_FORCE(x)                (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_CPU_SS_FORCE_SS_FORCE                   GENMASK(15,0)
#define  MSCC_X_CPU_SS_FORCE_SS_FORCE(x)                (((x) >> 0) & GENMASK(15,0))

#define MSCC_CPU_PCIE_SYS_CFG                MSCC_IOREG(MSCC_TO_CPU,0x2b)
#define  MSCC_F_CPU_PCIE_SYS_CFG_PCIE_RC_EP_MODE(x)     ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_SYS_CFG_PCIE_RC_EP_MODE        BIT(0)
#define  MSCC_X_CPU_PCIE_SYS_CFG_PCIE_RC_EP_MODE(x)     ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PROC_CTRL                   MSCC_IOREG(MSCC_TO_CPU,0x2c)
#define  MSCC_F_CPU_PROC_CTRL_AARCH64_MODE_ENA(x)       ((x) ? BIT(12) : 0)
#define  MSCC_M_CPU_PROC_CTRL_AARCH64_MODE_ENA          BIT(12)
#define  MSCC_X_CPU_PROC_CTRL_AARCH64_MODE_ENA(x)       ((x) & BIT(12) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_L2_RST_INVALIDATE_DIS(x)  ((x) ? BIT(11) : 0)
#define  MSCC_M_CPU_PROC_CTRL_L2_RST_INVALIDATE_DIS     BIT(11)
#define  MSCC_X_CPU_PROC_CTRL_L2_RST_INVALIDATE_DIS(x)  ((x) & BIT(11) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_L1_RST_INVALIDATE_DIS(x)  ((x) ? BIT(10) : 0)
#define  MSCC_M_CPU_PROC_CTRL_L1_RST_INVALIDATE_DIS     BIT(10)
#define  MSCC_X_CPU_PROC_CTRL_L1_RST_INVALIDATE_DIS(x)  ((x) & BIT(10) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_BE_EXCEP_MODE(x)          ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_PROC_CTRL_BE_EXCEP_MODE             BIT(9)
#define  MSCC_X_CPU_PROC_CTRL_BE_EXCEP_MODE(x)          ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_VINITHI(x)                ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_PROC_CTRL_VINITHI                   BIT(8)
#define  MSCC_X_CPU_PROC_CTRL_VINITHI(x)                ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_CFGTE(x)                  ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PROC_CTRL_CFGTE                     BIT(7)
#define  MSCC_X_CPU_PROC_CTRL_CFGTE(x)                  ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_CP15S_DISABLE(x)          ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PROC_CTRL_CP15S_DISABLE             BIT(6)
#define  MSCC_X_CPU_PROC_CTRL_CP15S_DISABLE(x)          ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_PROC_CRYPTO_DISABLE(x)    ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PROC_CTRL_PROC_CRYPTO_DISABLE       BIT(5)
#define  MSCC_X_CPU_PROC_CTRL_PROC_CRYPTO_DISABLE(x)    ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_ACP_CACHE_FORCE_ENA(x)    ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_PROC_CTRL_ACP_CACHE_FORCE_ENA       BIT(4)
#define  MSCC_X_CPU_PROC_CTRL_ACP_CACHE_FORCE_ENA(x)    ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_ACP_AWCACHE(x)            ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PROC_CTRL_ACP_AWCACHE               BIT(3)
#define  MSCC_X_CPU_PROC_CTRL_ACP_AWCACHE(x)            ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_ACP_ARCACHE(x)            ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PROC_CTRL_ACP_ARCACHE               BIT(2)
#define  MSCC_X_CPU_PROC_CTRL_ACP_ARCACHE(x)            ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_L2_FLUSH_REQ(x)           ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PROC_CTRL_L2_FLUSH_REQ              BIT(1)
#define  MSCC_X_CPU_PROC_CTRL_L2_FLUSH_REQ(x)           ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PROC_CTRL_ACP_DISABLE(x)            ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PROC_CTRL_ACP_DISABLE               BIT(0)
#define  MSCC_X_CPU_PROC_CTRL_ACP_DISABLE(x)            ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PROC_PERIPH_BASE            MSCC_IOREG(MSCC_TO_CPU,0x2d)
#define  MSCC_F_CPU_PROC_PERIPH_BASE_PERIPHBASE(x)      (GENMASK(21,0) & ((x) << 0))
#define  MSCC_M_CPU_PROC_PERIPH_BASE_PERIPHBASE         GENMASK(21,0)
#define  MSCC_X_CPU_PROC_PERIPH_BASE_PERIPHBASE(x)      (((x) >> 0) & GENMASK(21,0))

#define MSCC_CPU_CPU0_RVBAR_LSB              MSCC_IOREG(MSCC_TO_CPU,0x2e)
#define  MSCC_F_CPU_CPU0_RVBAR_LSB_CPU0_RVBAR_LSB(x)    (x)
#define  MSCC_M_CPU_CPU0_RVBAR_LSB_CPU0_RVBAR_LSB       0xffffffff
#define  MSCC_X_CPU_CPU0_RVBAR_LSB_CPU0_RVBAR_LSB(x)    (x)

#define MSCC_CPU_CPU0_RVBAR_MSB              MSCC_IOREG(MSCC_TO_CPU,0x2f)
#define  MSCC_F_CPU_CPU0_RVBAR_MSB_CPU0_RVBAR_MSB(x)    (GENMASK(5,0) & ((x) << 0))
#define  MSCC_M_CPU_CPU0_RVBAR_MSB_CPU0_RVBAR_MSB       GENMASK(5,0)
#define  MSCC_X_CPU_CPU0_RVBAR_MSB_CPU0_RVBAR_MSB(x)    (((x) >> 0) & GENMASK(5,0))

#define MSCC_CPU_CPU1_RVBAR_LSB              MSCC_IOREG(MSCC_TO_CPU,0x30)
#define  MSCC_F_CPU_CPU1_RVBAR_LSB_CPU1_RVBAR_LSB(x)    (x)
#define  MSCC_M_CPU_CPU1_RVBAR_LSB_CPU1_RVBAR_LSB       0xffffffff
#define  MSCC_X_CPU_CPU1_RVBAR_LSB_CPU1_RVBAR_LSB(x)    (x)

#define MSCC_CPU_CPU1_RVBAR_MSB              MSCC_IOREG(MSCC_TO_CPU,0x31)
#define  MSCC_F_CPU_CPU1_RVBAR_MSB_CPU1_RVBAR_MSB(x)    (GENMASK(5,0) & ((x) << 0))
#define  MSCC_M_CPU_CPU1_RVBAR_MSB_CPU1_RVBAR_MSB       GENMASK(5,0)
#define  MSCC_X_CPU_CPU1_RVBAR_MSB_CPU1_RVBAR_MSB(x)    (((x) >> 0) & GENMASK(5,0))

#define MSCC_CPU_PROC_STAT                   MSCC_IOREG(MSCC_TO_CPU,0x32)
#define  MSCC_F_CPU_PROC_STAT_DAP_JTAG_SW_MODE(x)       ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PROC_STAT_DAP_JTAG_SW_MODE          BIT(2)
#define  MSCC_X_CPU_PROC_STAT_DAP_JTAG_SW_MODE(x)       ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PROC_STAT_WFI_CORE_0(x)             ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PROC_STAT_WFI_CORE_0                BIT(1)
#define  MSCC_X_CPU_PROC_STAT_WFI_CORE_0(x)             ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PROC_STAT_WFI_CORE_1(x)             ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PROC_STAT_WFI_CORE_1                BIT(0)
#define  MSCC_X_CPU_PROC_STAT_WFI_CORE_1(x)             ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_TWI_CONFIG                  MSCC_IOREG(MSCC_TO_CPU,0x33)
#define  MSCC_F_CPU_TWI_CONFIG_TWI_CNT_RELOAD(x)        (GENMASK(8,1) & ((x) << 1))
#define  MSCC_M_CPU_TWI_CONFIG_TWI_CNT_RELOAD           GENMASK(8,1)
#define  MSCC_X_CPU_TWI_CONFIG_TWI_CNT_RELOAD(x)        (((x) >> 1) & GENMASK(7,0))
#define  MSCC_F_CPU_TWI_CONFIG_TWI_DELAY_ENABLE(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_TWI_CONFIG_TWI_DELAY_ENABLE         BIT(0)
#define  MSCC_X_CPU_TWI_CONFIG_TWI_DELAY_ENABLE(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_TWI_SPIKE_FILTER_CFG        MSCC_IOREG(MSCC_TO_CPU,0x34)
#define  MSCC_F_CPU_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG(x)  (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG     GENMASK(4,0)
#define  MSCC_X_CPU_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG(x)  (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_SPI_MST_CFG                 MSCC_IOREG(MSCC_TO_CPU,0x35)
#define  MSCC_F_CPU_SPI_MST_CFG_NUM_DUMMY_CLK_CYCLES(x)  (GENMASK(18,15) & ((x) << 15))
#define  MSCC_M_CPU_SPI_MST_CFG_NUM_DUMMY_CLK_CYCLES     GENMASK(18,15)
#define  MSCC_X_CPU_SPI_MST_CFG_NUM_DUMMY_CLK_CYCLES(x)  (((x) >> 15) & GENMASK(3,0))
#define  MSCC_F_CPU_SPI_MST_CFG_A32B_ENA(x)             ((x) ? BIT(14) : 0)
#define  MSCC_M_CPU_SPI_MST_CFG_A32B_ENA                BIT(14)
#define  MSCC_X_CPU_SPI_MST_CFG_A32B_ENA(x)             ((x) & BIT(14) ? 1 : 0)
#define  MSCC_F_CPU_SPI_MST_CFG_USE_4BYTE_READ_CMD(x)   ((x) ? BIT(13) : 0)
#define  MSCC_M_CPU_SPI_MST_CFG_USE_4BYTE_READ_CMD      BIT(13)
#define  MSCC_X_CPU_SPI_MST_CFG_USE_4BYTE_READ_CMD(x)   ((x) & BIT(13) ? 1 : 0)
#define  MSCC_F_CPU_SPI_MST_CFG_FAST_READ_ENA(x)        ((x) ? BIT(12) : 0)
#define  MSCC_M_CPU_SPI_MST_CFG_FAST_READ_ENA           BIT(12)
#define  MSCC_X_CPU_SPI_MST_CFG_FAST_READ_ENA(x)        ((x) & BIT(12) ? 1 : 0)
#define  MSCC_F_CPU_SPI_MST_CFG_SPI_PROTOCOL_MODE(x)    (GENMASK(11,10) & ((x) << 10))
#define  MSCC_M_CPU_SPI_MST_CFG_SPI_PROTOCOL_MODE       GENMASK(11,10)
#define  MSCC_X_CPU_SPI_MST_CFG_SPI_PROTOCOL_MODE(x)    (((x) >> 10) & GENMASK(1,0))
#define  MSCC_F_CPU_SPI_MST_CFG_CS_DESELECT_TIME(x)     (GENMASK(9,5) & ((x) << 5))
#define  MSCC_M_CPU_SPI_MST_CFG_CS_DESELECT_TIME        GENMASK(9,5)
#define  MSCC_X_CPU_SPI_MST_CFG_CS_DESELECT_TIME(x)     (((x) >> 5) & GENMASK(4,0))
#define  MSCC_F_CPU_SPI_MST_CFG_CLK_DIV(x)              (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_SPI_MST_CFG_CLK_DIV                 GENMASK(4,0)
#define  MSCC_X_CPU_SPI_MST_CFG_CLK_DIV(x)              (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_SPI_MST_STATUS(ri)          MSCC_IOREG(MSCC_TO_CPU,0x36 + (ri))
#define  MSCC_F_CPU_SPI_MST_STATUS_UNSUP_ERR(x)         ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_SPI_MST_STATUS_UNSUP_ERR            BIT(0)
#define  MSCC_X_CPU_SPI_MST_STATUS_UNSUP_ERR(x)         ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_SW_MODE                     MSCC_IOREG(MSCC_TO_CPU,0x3a)
#define  MSCC_F_CPU_SW_MODE_SW_PIN_CTRL_MODE(x)         ((x) ? BIT(22) : 0)
#define  MSCC_M_CPU_SW_MODE_SW_PIN_CTRL_MODE            BIT(22)
#define  MSCC_X_CPU_SW_MODE_SW_PIN_CTRL_MODE(x)         ((x) & BIT(22) ? 1 : 0)
#define  MSCC_F_CPU_SW_MODE_SW_SPI_SCK(x)               ((x) ? BIT(21) : 0)
#define  MSCC_M_CPU_SW_MODE_SW_SPI_SCK                  BIT(21)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_SCK(x)               ((x) & BIT(21) ? 1 : 0)
#define  MSCC_F_CPU_SW_MODE_SW_SPI_SCK_OE(x)            ((x) ? BIT(20) : 0)
#define  MSCC_M_CPU_SW_MODE_SW_SPI_SCK_OE               BIT(20)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_SCK_OE(x)            ((x) & BIT(20) ? 1 : 0)
#define  MSCC_F_CPU_SW_MODE_SW_SPI_SDQ(x)               (GENMASK(19,16) & ((x) << 16))
#define  MSCC_M_CPU_SW_MODE_SW_SPI_SDQ                  GENMASK(19,16)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_SDQ(x)               (((x) >> 16) & GENMASK(3,0))
#define  MSCC_F_CPU_SW_MODE_SW_SPI_SDQ_OE(x)            (GENMASK(15,12) & ((x) << 12))
#define  MSCC_M_CPU_SW_MODE_SW_SPI_SDQ_OE               GENMASK(15,12)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_SDQ_OE(x)            (((x) >> 12) & GENMASK(3,0))
#define  MSCC_F_CPU_SW_MODE_SW_SPI_CS(x)                (GENMASK(11,8) & ((x) << 8))
#define  MSCC_M_CPU_SW_MODE_SW_SPI_CS                   GENMASK(11,8)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_CS(x)                (((x) >> 8) & GENMASK(3,0))
#define  MSCC_F_CPU_SW_MODE_SW_SPI_CS_OE(x)             (GENMASK(7,4) & ((x) << 4))
#define  MSCC_M_CPU_SW_MODE_SW_SPI_CS_OE                GENMASK(7,4)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_CS_OE(x)             (((x) >> 4) & GENMASK(3,0))
#define  MSCC_F_CPU_SW_MODE_SW_SPI_SDQ_IN(x)            (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_SW_MODE_SW_SPI_SDQ_IN               GENMASK(3,0)
#define  MSCC_X_CPU_SW_MODE_SW_SPI_SDQ_IN(x)            (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PI_MST_CFG                  MSCC_IOREG(MSCC_TO_CPU,0x3b)
#define  MSCC_F_CPU_PI_MST_CFG_ATE_MODE_DIS(x)          ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PI_MST_CFG_ATE_MODE_DIS             BIT(7)
#define  MSCC_X_CPU_PI_MST_CFG_ATE_MODE_DIS(x)          ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CFG_CLK_POL(x)               ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PI_MST_CFG_CLK_POL                  BIT(6)
#define  MSCC_X_CPU_PI_MST_CFG_CLK_POL(x)               ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CFG_TRISTATE_CTRL(x)         ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PI_MST_CFG_TRISTATE_CTRL            BIT(5)
#define  MSCC_X_CPU_PI_MST_CFG_TRISTATE_CTRL(x)         ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CFG_CLK_DIV(x)               (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_PI_MST_CFG_CLK_DIV                  GENMASK(4,0)
#define  MSCC_X_CPU_PI_MST_CFG_CLK_DIV(x)               (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_PI_MST_CTRL                 MSCC_IOREG(MSCC_TO_CPU,0x3c)
#define  MSCC_F_CPU_PI_MST_CTRL_DATA_WID(x)             ((x) ? BIT(23) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_DATA_WID                BIT(23)
#define  MSCC_X_CPU_PI_MST_CTRL_DATA_WID(x)             ((x) & BIT(23) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_DEVICE_PACED_XFER_ENA(x)  ((x) ? BIT(22) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_DEVICE_PACED_XFER_ENA     BIT(22)
#define  MSCC_X_CPU_PI_MST_CTRL_DEVICE_PACED_XFER_ENA(x)  ((x) & BIT(22) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT_ENA(x)  ((x) ? BIT(21) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT_ENA     BIT(21)
#define  MSCC_X_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT_ENA(x)  ((x) & BIT(21) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT(x)  (GENMASK(20,18) & ((x) << 18))
#define  MSCC_M_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT     GENMASK(20,18)
#define  MSCC_X_CPU_PI_MST_CTRL_DEVICE_PACED_TIMEOUT(x)  (((x) >> 18) & GENMASK(2,0))
#define  MSCC_F_CPU_PI_MST_CTRL_CS_TRISTATE_CTRL(x)     ((x) ? BIT(17) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_CS_TRISTATE_CTRL        BIT(17)
#define  MSCC_X_CPU_PI_MST_CTRL_CS_TRISTATE_CTRL(x)     ((x) & BIT(17) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_DONE_POL(x)             ((x) ? BIT(16) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_DONE_POL                BIT(16)
#define  MSCC_X_CPU_PI_MST_CTRL_DONE_POL(x)             ((x) & BIT(16) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_SMPL_ON_DONE(x)         ((x) ? BIT(15) : 0)
#define  MSCC_M_CPU_PI_MST_CTRL_SMPL_ON_DONE            BIT(15)
#define  MSCC_X_CPU_PI_MST_CTRL_SMPL_ON_DONE(x)         ((x) & BIT(15) ? 1 : 0)
#define  MSCC_F_CPU_PI_MST_CTRL_WAITCC(x)               (GENMASK(14,7) & ((x) << 7))
#define  MSCC_M_CPU_PI_MST_CTRL_WAITCC                  GENMASK(14,7)
#define  MSCC_X_CPU_PI_MST_CTRL_WAITCC(x)               (((x) >> 7) & GENMASK(7,0))
#define  MSCC_F_CPU_PI_MST_CTRL_CSCC(x)                 (GENMASK(6,5) & ((x) << 5))
#define  MSCC_M_CPU_PI_MST_CTRL_CSCC                    GENMASK(6,5)
#define  MSCC_X_CPU_PI_MST_CTRL_CSCC(x)                 (((x) >> 5) & GENMASK(1,0))
#define  MSCC_F_CPU_PI_MST_CTRL_OECC(x)                 (GENMASK(4,3) & ((x) << 3))
#define  MSCC_M_CPU_PI_MST_CTRL_OECC                    GENMASK(4,3)
#define  MSCC_X_CPU_PI_MST_CTRL_OECC(x)                 (((x) >> 3) & GENMASK(1,0))
#define  MSCC_F_CPU_PI_MST_CTRL_HLDCC(x)                (GENMASK(2,0) & ((x) << 0))
#define  MSCC_M_CPU_PI_MST_CTRL_HLDCC                   GENMASK(2,0)
#define  MSCC_X_CPU_PI_MST_CTRL_HLDCC(x)                (((x) >> 0) & GENMASK(2,0))

#define MSCC_CPU_PI_MST_STATUS               MSCC_IOREG(MSCC_TO_CPU,0x3d)
#define  MSCC_F_CPU_PI_MST_STATUS_TIMEOUT_ERR_STICKY(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PI_MST_STATUS_TIMEOUT_ERR_STICKY     BIT(0)
#define  MSCC_X_CPU_PI_MST_STATUS_TIMEOUT_ERR_STICKY(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PI_SLV_CFG                  MSCC_IOREG(MSCC_TO_CPU,0x3e)
#define  MSCC_F_CPU_PI_SLV_CFG_DONEPOL_VAL(x)           ((x) ? BIT(24) : 0)
#define  MSCC_M_CPU_PI_SLV_CFG_DONEPOL_VAL              BIT(24)
#define  MSCC_X_CPU_PI_SLV_CFG_DONEPOL_VAL(x)           ((x) & BIT(24) ? 1 : 0)
#define  MSCC_F_CPU_PI_SLV_CFG_DONEPOL_SET(x)           ((x) ? BIT(23) : 0)
#define  MSCC_M_CPU_PI_SLV_CFG_DONEPOL_SET              BIT(23)
#define  MSCC_X_CPU_PI_SLV_CFG_DONEPOL_SET(x)           ((x) & BIT(23) ? 1 : 0)
#define  MSCC_F_CPU_PI_SLV_CFG_BIGENDIAN(x)             ((x) ? BIT(22) : 0)
#define  MSCC_M_CPU_PI_SLV_CFG_BIGENDIAN                BIT(22)
#define  MSCC_X_CPU_PI_SLV_CFG_BIGENDIAN(x)             ((x) & BIT(22) ? 1 : 0)
#define  MSCC_F_CPU_PI_SLV_CFG_DONEPARK(x)              (GENMASK(21,16) & ((x) << 16))
#define  MSCC_M_CPU_PI_SLV_CFG_DONEPARK                 GENMASK(21,16)
#define  MSCC_X_CPU_PI_SLV_CFG_DONEPARK(x)              (((x) >> 16) & GENMASK(5,0))
#define  MSCC_F_CPU_PI_SLV_CFG_DONEWAIT(x)              (GENMASK(15,8) & ((x) << 8))
#define  MSCC_M_CPU_PI_SLV_CFG_DONEWAIT                 GENMASK(15,8)
#define  MSCC_X_CPU_PI_SLV_CFG_DONEWAIT(x)              (((x) >> 8) & GENMASK(7,0))
#define  MSCC_F_CPU_PI_SLV_CFG_CSWAIT(x)                (GENMASK(7,0) & ((x) << 0))
#define  MSCC_M_CPU_PI_SLV_CFG_CSWAIT                   GENMASK(7,0)
#define  MSCC_X_CPU_PI_SLV_CFG_CSWAIT(x)                (((x) >> 0) & GENMASK(7,0))

#define MSCC_CPU_MIIM_SLAVE_CFG              MSCC_IOREG(MSCC_TO_CPU,0x3f)
#define  MSCC_F_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG(x)  (GENMASK(5,1) & ((x) << 1))
#define  MSCC_M_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG     GENMASK(5,1)
#define  MSCC_X_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG(x)  (((x) >> 1) & GENMASK(4,0))
#define  MSCC_F_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_ENA(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_ENA     BIT(0)
#define  MSCC_X_CPU_MIIM_SLAVE_CFG_SPIKE_FILTER_ENA(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_VCORE_ACC_CFG               MSCC_IOREG(MSCC_TO_CPU,0x40)
#define  MSCC_F_CPU_VCORE_ACC_CFG_DIS_VA_RD_ERR(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_VCORE_ACC_CFG_DIS_VA_RD_ERR         BIT(0)
#define  MSCC_X_CPU_VCORE_ACC_CFG_DIS_VA_RD_ERR(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_MSIX_ACC_CFG                MSCC_IOREG(MSCC_TO_CPU,0x41)
#define  MSCC_F_CPU_MSIX_ACC_CFG_DIS_MSIX_RD_ERR(x)     ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_MSIX_ACC_CFG_DIS_MSIX_RD_ERR        BIT(0)
#define  MSCC_X_CPU_MSIX_ACC_CFG_DIS_MSIX_RD_ERR(x)     ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_EXT_IF_ACC_STAT             MSCC_IOREG(MSCC_TO_CPU,0x42)
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_VRAP_ACC_STAT(x)    (GENMASK(2,0) & ((x) << 0))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_VRAP_ACC_STAT       GENMASK(2,0)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_VRAP_ACC_STAT(x)    (((x) >> 0) & GENMASK(2,0))
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_SI_ACC_STAT(x)      (GENMASK(6,4) & ((x) << 4))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_SI_ACC_STAT         GENMASK(6,4)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_SI_ACC_STAT(x)      (((x) >> 4) & GENMASK(2,0))
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_PI_ACC_STAT(x)      (GENMASK(10,8) & ((x) << 8))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_PI_ACC_STAT         GENMASK(10,8)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_PI_ACC_STAT(x)      (((x) >> 8) & GENMASK(2,0))
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_MIIM_ACC_STAT(x)    (GENMASK(14,12) & ((x) << 12))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_MIIM_ACC_STAT       GENMASK(14,12)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_MIIM_ACC_STAT(x)    (((x) >> 12) & GENMASK(2,0))
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_VA_ACC_STAT(x)      (GENMASK(18,16) & ((x) << 16))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_VA_ACC_STAT         GENMASK(18,16)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_VA_ACC_STAT(x)      (((x) >> 16) & GENMASK(2,0))
#define  MSCC_F_CPU_EXT_IF_ACC_STAT_MSIX_ACC_STAT(x)    (GENMASK(22,20) & ((x) << 20))
#define  MSCC_M_CPU_EXT_IF_ACC_STAT_MSIX_ACC_STAT       GENMASK(22,20)
#define  MSCC_X_CPU_EXT_IF_ACC_STAT_MSIX_ACC_STAT(x)    (((x) >> 20) & GENMASK(2,0))

#define MSCC_CPU_PCIE_CTRL                   MSCC_IOREG(MSCC_TO_CPU,0x43)
#define  MSCC_F_CPU_PCIE_CTRL_POWERUP(x)                (GENMASK(5,4) & ((x) << 4))
#define  MSCC_M_CPU_PCIE_CTRL_POWERUP                   GENMASK(5,4)
#define  MSCC_X_CPU_PCIE_CTRL_POWERUP(x)                (((x) >> 4) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIE_CTRL_POWERDOWN(x)              ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_CTRL_POWERDOWN                 BIT(3)
#define  MSCC_X_CPU_PCIE_CTRL_POWERDOWN(x)              ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CTRL_UNLOCK_MSG_TX(x)          ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_CTRL_UNLOCK_MSG_TX             BIT(2)
#define  MSCC_X_CPU_PCIE_CTRL_UNLOCK_MSG_TX(x)          ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CTRL_FLUSH_ENA(x)              ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_CTRL_FLUSH_ENA                 BIT(1)
#define  MSCC_X_CPU_PCIE_CTRL_FLUSH_ENA(x)              ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CTRL_INIT_RST_ENA(x)           ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_CTRL_INIT_RST_ENA              BIT(0)
#define  MSCC_X_CPU_PCIE_CTRL_INIT_RST_ENA(x)           ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_CFG                    MSCC_IOREG(MSCC_TO_CPU,0x44)
#define  MSCC_F_CPU_PCIE_CFG_CG_DIS(x)                  ((x) ? BIT(11) : 0)
#define  MSCC_M_CPU_PCIE_CFG_CG_DIS                     BIT(11)
#define  MSCC_X_CPU_PCIE_CFG_CG_DIS(x)                  ((x) & BIT(11) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_MEM_CG_DIS(x)              ((x) ? BIT(10) : 0)
#define  MSCC_M_CPU_PCIE_CFG_MEM_CG_DIS                 BIT(10)
#define  MSCC_X_CPU_PCIE_CFG_MEM_CG_DIS(x)              ((x) & BIT(10) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_CONF_REQ_RETRY_ENA(x)      ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_PCIE_CFG_CONF_REQ_RETRY_ENA         BIT(9)
#define  MSCC_X_CPU_PCIE_CFG_CONF_REQ_RETRY_ENA(x)      ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_PCIE_DBI_ACCESS_ENA(x)     (GENMASK(8,7) & ((x) << 7))
#define  MSCC_M_CPU_PCIE_CFG_PCIE_DBI_ACCESS_ENA        GENMASK(8,7)
#define  MSCC_X_CPU_PCIE_CFG_PCIE_DBI_ACCESS_ENA(x)     (((x) >> 7) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIE_CFG_LTSSM_DIS(x)               ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PCIE_CFG_LTSSM_DIS                  BIT(6)
#define  MSCC_X_CPU_PCIE_CFG_LTSSM_DIS(x)               ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_MEM_RING_CORE_ENA(x)       ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PCIE_CFG_MEM_RING_CORE_ENA          BIT(5)
#define  MSCC_X_CPU_PCIE_CFG_MEM_RING_CORE_ENA(x)       ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_MSTR_XFER_PENDING(x)       ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_PCIE_CFG_MSTR_XFER_PENDING          BIT(4)
#define  MSCC_X_CPU_PCIE_CFG_MSTR_XFER_PENDING(x)       ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_WAKE_DIS(x)                ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_CFG_WAKE_DIS                   BIT(3)
#define  MSCC_X_CPU_PCIE_CFG_WAKE_DIS(x)                ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_WAKE_POL(x)                ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_CFG_WAKE_POL                   BIT(2)
#define  MSCC_X_CPU_PCIE_CFG_WAKE_POL(x)                ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_WAKE_OE(x)                 ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_CFG_WAKE_OE                    BIT(1)
#define  MSCC_X_CPU_PCIE_CFG_WAKE_OE(x)                 ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_CFG_BYPASS_INBOUND_AT(x)       ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_CFG_BYPASS_INBOUND_AT          BIT(0)
#define  MSCC_X_CPU_PCIE_CFG_BYPASS_INBOUND_AT(x)       ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_STAT                   MSCC_IOREG(MSCC_TO_CPU,0x45)
#define  MSCC_F_CPU_PCIE_STAT_LTSSM_STATE(x)            (GENMASK(14,9) & ((x) << 9))
#define  MSCC_M_CPU_PCIE_STAT_LTSSM_STATE               GENMASK(14,9)
#define  MSCC_X_CPU_PCIE_STAT_LTSSM_STATE(x)            (((x) >> 9) & GENMASK(5,0))
#define  MSCC_F_CPU_PCIE_STAT_LINK_STATE(x)             (GENMASK(8,6) & ((x) << 6))
#define  MSCC_M_CPU_PCIE_STAT_LINK_STATE                GENMASK(8,6)
#define  MSCC_X_CPU_PCIE_STAT_LINK_STATE(x)             (((x) >> 6) & GENMASK(2,0))
#define  MSCC_F_CPU_PCIE_STAT_PM_STATE(x)               (GENMASK(5,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_STAT_PM_STATE                  GENMASK(5,0)
#define  MSCC_X_CPU_PCIE_STAT_PM_STATE(x)               (((x) >> 0) & GENMASK(5,0))

#define MSCC_CPU_PCIE_AUX_CFG                MSCC_IOREG(MSCC_TO_CPU,0x46)
#define  MSCC_F_CPU_PCIE_AUX_CFG_AUX_POWER_VAL(x)       ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_AUX_CFG_AUX_POWER_VAL          BIT(0)
#define  MSCC_X_CPU_PCIE_AUX_CFG_AUX_POWER_VAL(x)       ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_DBG_STAT               MSCC_IOREG(MSCC_TO_CPU,0x47)
#define  MSCC_F_CPU_PCIE_DBG_STAT_PM_L2_EXIT(x)         ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_DBG_STAT_PM_L2_EXIT            BIT(2)
#define  MSCC_X_CPU_PCIE_DBG_STAT_PM_L2_EXIT(x)         ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_DBG_STAT_DATA_LINK_LAYER_UP(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_DBG_STAT_DATA_LINK_LAYER_UP     BIT(1)
#define  MSCC_X_CPU_PCIE_DBG_STAT_DATA_LINK_LAYER_UP(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_DBG_STAT_PHY_LAYER_UP(x)       ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_DBG_STAT_PHY_LAYER_UP          BIT(0)
#define  MSCC_X_CPU_PCIE_DBG_STAT_PHY_LAYER_UP(x)       ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIEMST_REPLY_INFO          MSCC_IOREG(MSCC_TO_CPU,0x48)
#define  MSCC_F_CPU_PCIEMST_REPLY_INFO_MST_REPLY_INFO(x)  (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIEMST_REPLY_INFO_MST_REPLY_INFO     GENMASK(4,0)
#define  MSCC_X_CPU_PCIEMST_REPLY_INFO_MST_REPLY_INFO(x)  (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_PCIEMST_PF1_BAR0_OFFSET_LOW  MSCC_IOREG(MSCC_TO_CPU,0x49)
#define  MSCC_F_CPU_PCIEMST_PF1_BAR0_OFFSET_LOW_PF1_BAR0_OFFSET_LOW(x)  (GENMASK(31,8) & ((x) << 8))
#define  MSCC_M_CPU_PCIEMST_PF1_BAR0_OFFSET_LOW_PF1_BAR0_OFFSET_LOW     GENMASK(31,8)
#define  MSCC_X_CPU_PCIEMST_PF1_BAR0_OFFSET_LOW_PF1_BAR0_OFFSET_LOW(x)  (((x) >> 8) & GENMASK(23,0))

#define MSCC_CPU_PCIEMST_PF1_BAR0_OFFSET_HIGH  MSCC_IOREG(MSCC_TO_CPU,0x4a)
#define  MSCC_F_CPU_PCIEMST_PF1_BAR0_OFFSET_HIGH_PF1_BAR0_OFFSET_HIGH(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIEMST_PF1_BAR0_OFFSET_HIGH_PF1_BAR0_OFFSET_HIGH     GENMASK(3,0)
#define  MSCC_X_CPU_PCIEMST_PF1_BAR0_OFFSET_HIGH_PF1_BAR0_OFFSET_HIGH(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PCIEMST_PF1_BAR0_MASK_LOW   MSCC_IOREG(MSCC_TO_CPU,0x4b)
#define  MSCC_F_CPU_PCIEMST_PF1_BAR0_MASK_LOW_PF1_BAR0_MASK_LOW(x)  (GENMASK(31,8) & ((x) << 8))
#define  MSCC_M_CPU_PCIEMST_PF1_BAR0_MASK_LOW_PF1_BAR0_MASK_LOW     GENMASK(31,8)
#define  MSCC_X_CPU_PCIEMST_PF1_BAR0_MASK_LOW_PF1_BAR0_MASK_LOW(x)  (((x) >> 8) & GENMASK(23,0))

#define MSCC_CPU_PCIEMST_PF1_BAR0_MASK_HIGH  MSCC_IOREG(MSCC_TO_CPU,0x4c)
#define  MSCC_F_CPU_PCIEMST_PF1_BAR0_MASK_HIGH_PF1_BAR0_MASK_HIGH(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIEMST_PF1_BAR0_MASK_HIGH_PF1_BAR0_MASK_HIGH     GENMASK(3,0)
#define  MSCC_X_CPU_PCIEMST_PF1_BAR0_MASK_HIGH_PF1_BAR0_MASK_HIGH(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PCIEMST_PF0_BAR2_OFFSET_LOW  MSCC_IOREG(MSCC_TO_CPU,0x4d)
#define  MSCC_F_CPU_PCIEMST_PF0_BAR2_OFFSET_LOW_PF0_BAR2_OFFSET_LOW(x)  (GENMASK(31,8) & ((x) << 8))
#define  MSCC_M_CPU_PCIEMST_PF0_BAR2_OFFSET_LOW_PF0_BAR2_OFFSET_LOW     GENMASK(31,8)
#define  MSCC_X_CPU_PCIEMST_PF0_BAR2_OFFSET_LOW_PF0_BAR2_OFFSET_LOW(x)  (((x) >> 8) & GENMASK(23,0))

#define MSCC_CPU_PCIEMST_PF0_BAR2_OFFSET_HIGH  MSCC_IOREG(MSCC_TO_CPU,0x4e)
#define  MSCC_F_CPU_PCIEMST_PF0_BAR2_OFFSET_HIGH_PF0_BAR2_OFFSET_HIGH(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIEMST_PF0_BAR2_OFFSET_HIGH_PF0_BAR2_OFFSET_HIGH     GENMASK(3,0)
#define  MSCC_X_CPU_PCIEMST_PF0_BAR2_OFFSET_HIGH_PF0_BAR2_OFFSET_HIGH(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PCIEMST_PF0_BAR2_MASK_LOW   MSCC_IOREG(MSCC_TO_CPU,0x4f)
#define  MSCC_F_CPU_PCIEMST_PF0_BAR2_MASK_LOW_PF0_BAR2_MASK_LOW(x)  (GENMASK(31,8) & ((x) << 8))
#define  MSCC_M_CPU_PCIEMST_PF0_BAR2_MASK_LOW_PF0_BAR2_MASK_LOW     GENMASK(31,8)
#define  MSCC_X_CPU_PCIEMST_PF0_BAR2_MASK_LOW_PF0_BAR2_MASK_LOW(x)  (((x) >> 8) & GENMASK(23,0))

#define MSCC_CPU_PCIEMST_PF0_BAR2_MASK_HIGH  MSCC_IOREG(MSCC_TO_CPU,0x50)
#define  MSCC_F_CPU_PCIEMST_PF0_BAR2_MASK_HIGH_PF0_BAR2_MASK_HIGH(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIEMST_PF0_BAR2_MASK_HIGH_PF0_BAR2_MASK_HIGH     GENMASK(3,0)
#define  MSCC_X_CPU_PCIEMST_PF0_BAR2_MASK_HIGH_PF0_BAR2_MASK_HIGH(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PCIESLV_IATU_BYPASS         MSCC_IOREG(MSCC_TO_CPU,0x51)
#define  MSCC_F_CPU_PCIESLV_IATU_BYPASS_WR_REQ_BYPASS_ENA(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIESLV_IATU_BYPASS_WR_REQ_BYPASS_ENA     BIT(1)
#define  MSCC_X_CPU_PCIESLV_IATU_BYPASS_WR_REQ_BYPASS_ENA(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIESLV_IATU_BYPASS_RD_REQ_BYPASS_ENA(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIESLV_IATU_BYPASS_RD_REQ_BYPASS_ENA     BIT(0)
#define  MSCC_X_CPU_PCIESLV_IATU_BYPASS_RD_REQ_BYPASS_ENA(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIESLV_FDMA                MSCC_IOREG(MSCC_TO_CPU,0x52)
#define  MSCC_F_CPU_PCIESLV_FDMA_FDMA_TC(x)             (GENMASK(4,2) & ((x) << 2))
#define  MSCC_M_CPU_PCIESLV_FDMA_FDMA_TC                GENMASK(4,2)
#define  MSCC_X_CPU_PCIESLV_FDMA_FDMA_TC(x)             (((x) >> 2) & GENMASK(2,0))
#define  MSCC_F_CPU_PCIESLV_FDMA_FDMA_ATTR(x)           (GENMASK(1,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIESLV_FDMA_FDMA_ATTR              GENMASK(1,0)
#define  MSCC_X_CPU_PCIESLV_FDMA_FDMA_ATTR(x)           (((x) >> 0) & GENMASK(1,0))

#define MSCC_CPU_PCIESLV_CPU                 MSCC_IOREG(MSCC_TO_CPU,0x53)
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_RESERVED2(x)        ((x) ? BIT(21) : 0)
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_RESERVED2           BIT(21)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_RESERVED2(x)        ((x) & BIT(21) ? 1 : 0)
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_MSG_CODE(x)         (GENMASK(20,13) & ((x) << 13))
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_MSG_CODE            GENMASK(20,13)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_MSG_CODE(x)         (((x) >> 13) & GENMASK(7,0))
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_TC(x)               (GENMASK(12,10) & ((x) << 10))
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_TC                  GENMASK(12,10)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_TC(x)               (((x) >> 10) & GENMASK(2,0))
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_ATTR(x)             (GENMASK(9,8) & ((x) << 8))
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_ATTR                GENMASK(9,8)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_ATTR(x)             (((x) >> 8) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_RESERVED1(x)        ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_RESERVED1           BIT(7)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_RESERVED1(x)        ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_EP(x)               ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_EP                  BIT(6)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_EP(x)               ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_RESERVED0(x)        ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_RESERVED0           BIT(5)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_RESERVED0(x)        ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PCIESLV_CPU_CPU_TYPE(x)             (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIESLV_CPU_CPU_TYPE                GENMASK(4,0)
#define  MSCC_X_CPU_PCIESLV_CPU_CPU_TYPE(x)             (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_PCIESLV_MSG_3DW             MSCC_IOREG(MSCC_TO_CPU,0x54)
#define  MSCC_F_CPU_PCIESLV_MSG_3DW_PCIESLV_MSG_3DW(x)  (x)
#define  MSCC_M_CPU_PCIESLV_MSG_3DW_PCIESLV_MSG_3DW     0xffffffff
#define  MSCC_X_CPU_PCIESLV_MSG_3DW_PCIESLV_MSG_3DW(x)  (x)

#define MSCC_CPU_PCIESLV_MSG_4DW             MSCC_IOREG(MSCC_TO_CPU,0x55)
#define  MSCC_F_CPU_PCIESLV_MSG_4DW_PCIESLV_MSG_4DW(x)  (x)
#define  MSCC_M_CPU_PCIESLV_MSG_4DW_PCIESLV_MSG_4DW     0xffffffff
#define  MSCC_X_CPU_PCIESLV_MSG_4DW_PCIESLV_MSG_4DW(x)  (x)

#define MSCC_CPU_PCIERST_CFG                 MSCC_IOREG(MSCC_TO_CPU,0x56)
#define  MSCC_F_CPU_PCIERST_CFG_POWERONRST_FORCE(x)     ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIERST_CFG_POWERONRST_FORCE        BIT(2)
#define  MSCC_X_CPU_PCIERST_CFG_POWERONRST_FORCE(x)     ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIERST_CFG_POWERONRST_VAL(x)       ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIERST_CFG_POWERONRST_VAL          BIT(1)
#define  MSCC_X_CPU_PCIERST_CFG_POWERONRST_VAL(x)       ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIERST_CFG_AMBA_RST_DIS(x)         ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIERST_CFG_AMBA_RST_DIS            BIT(0)
#define  MSCC_X_CPU_PCIERST_CFG_AMBA_RST_DIS(x)         ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_MSG_STICKY             MSCC_IOREG(MSCC_TO_CPU,0x57)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_CORR_ERR_STICKY(x)  ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_CORR_ERR_STICKY     BIT(7)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_CORR_ERR_STICKY(x)  ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_FATAL_ERR_STICKY(x)  ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_FATAL_ERR_STICKY     BIT(6)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_FATAL_ERR_STICKY(x)  ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_NONFATAL_ERR_STICKY(x)  ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_NONFATAL_ERR_STICKY     BIT(5)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_NONFATAL_ERR_STICKY(x)  ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_UNLOCK_MSG_STICKY(x)  ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_UNLOCK_MSG_STICKY     BIT(4)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_UNLOCK_MSG_STICKY(x)  ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_PM_PME_MSG_STICKY(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_PM_PME_MSG_STICKY     BIT(3)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_PM_PME_MSG_STICKY(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_PM_TO_ACK_MSG_STICKY(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_PM_TO_ACK_MSG_STICKY     BIT(2)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_PM_TO_ACK_MSG_STICKY(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_PM_TURNOFF_MSG_STICKY(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_PM_TURNOFF_MSG_STICKY     BIT(1)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_PM_TURNOFF_MSG_STICKY(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_MSG_STICKY_VENDOR_MSG_STICKY(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_MSG_STICKY_VENDOR_MSG_STICKY     BIT(0)
#define  MSCC_X_CPU_PCIE_MSG_STICKY_VENDOR_MSG_STICKY(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_MSG_PAYLOAD_LOW        MSCC_IOREG(MSCC_TO_CPU,0x58)
#define  MSCC_F_CPU_PCIE_MSG_PAYLOAD_LOW_VDM_MSG_PAYLOAD_LOW(x)  (x)
#define  MSCC_M_CPU_PCIE_MSG_PAYLOAD_LOW_VDM_MSG_PAYLOAD_LOW     0xffffffff
#define  MSCC_X_CPU_PCIE_MSG_PAYLOAD_LOW_VDM_MSG_PAYLOAD_LOW(x)  (x)

#define MSCC_CPU_PCIE_MSG_PAYLOAD_HIGH       MSCC_IOREG(MSCC_TO_CPU,0x59)
#define  MSCC_F_CPU_PCIE_MSG_PAYLOAD_HIGH_VDM_MSG_PAYLOAD_HIGH(x)  (x)
#define  MSCC_M_CPU_PCIE_MSG_PAYLOAD_HIGH_VDM_MSG_PAYLOAD_HIGH     0xffffffff
#define  MSCC_X_CPU_PCIE_MSG_PAYLOAD_HIGH_VDM_MSG_PAYLOAD_HIGH(x)  (x)

#define MSCC_CPU_PCIE_MSG_HDR_INFO_0         MSCC_IOREG(MSCC_TO_CPU,0x5a)
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_0_CORR_MSG_REQ_ID(x)  (GENMASK(31,16) & ((x) << 16))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_0_CORR_MSG_REQ_ID     GENMASK(31,16)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_0_CORR_MSG_REQ_ID(x)  (((x) >> 16) & GENMASK(15,0))
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_0_NF_MSG_REQ_ID(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_0_NF_MSG_REQ_ID     GENMASK(15,0)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_0_NF_MSG_REQ_ID(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_CPU_PCIE_MSG_HDR_INFO_1         MSCC_IOREG(MSCC_TO_CPU,0x5b)
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_1_F_MSG_REQ_ID(x)  (GENMASK(31,16) & ((x) << 16))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_1_F_MSG_REQ_ID     GENMASK(31,16)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_1_F_MSG_REQ_ID(x)  (((x) >> 16) & GENMASK(15,0))
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_1_PME_MSG_REQ_ID(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_1_PME_MSG_REQ_ID     GENMASK(15,0)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_1_PME_MSG_REQ_ID(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_CPU_PCIE_MSG_HDR_INFO_2         MSCC_IOREG(MSCC_TO_CPU,0x5c)
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_2_ACK_MSG_REQ_ID(x)  (GENMASK(31,16) & ((x) << 16))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_2_ACK_MSG_REQ_ID     GENMASK(31,16)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_2_ACK_MSG_REQ_ID(x)  (((x) >> 16) & GENMASK(15,0))
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_2_TURNOFF_MSG_REQ_ID(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_2_TURNOFF_MSG_REQ_ID     GENMASK(15,0)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_2_TURNOFF_MSG_REQ_ID(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_CPU_PCIE_MSG_HDR_INFO_3         MSCC_IOREG(MSCC_TO_CPU,0x5d)
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_3_UNLOCK_MSG_REQ_ID(x)  (GENMASK(31,16) & ((x) << 16))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_3_UNLOCK_MSG_REQ_ID     GENMASK(31,16)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_3_UNLOCK_MSG_REQ_ID(x)  (((x) >> 16) & GENMASK(15,0))
#define  MSCC_F_CPU_PCIE_MSG_HDR_INFO_3_VDM_MSG_REQ_ID(x)  (GENMASK(15,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_MSG_HDR_INFO_3_VDM_MSG_REQ_ID     GENMASK(15,0)
#define  MSCC_X_CPU_PCIE_MSG_HDR_INFO_3_VDM_MSG_REQ_ID(x)  (((x) >> 0) & GENMASK(15,0))

#define MSCC_CPU_PCIE_INTR                   MSCC_IOREG(MSCC_TO_CPU,0x5e)
#define  MSCC_F_CPU_PCIE_INTR_INTR_SYS_ERR_RC(x)        ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_SYS_ERR_RC           BIT(9)
#define  MSCC_X_CPU_PCIE_INTR_INTR_SYS_ERR_RC(x)        ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_EARLY_LINK_DOWN(x)   ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_EARLY_LINK_DOWN      BIT(8)
#define  MSCC_X_CPU_PCIE_INTR_INTR_EARLY_LINK_DOWN(x)   ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_LTSSM_STATE(x)       ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_LTSSM_STATE          BIT(7)
#define  MSCC_X_CPU_PCIE_INTR_INTR_LTSSM_STATE(x)       ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_LINK_STATE(x)        ((x) ? BIT(6) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_LINK_STATE           BIT(6)
#define  MSCC_X_CPU_PCIE_INTR_INTR_LINK_STATE(x)        ((x) & BIT(6) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_PM_STATE(x)          (GENMASK(5,4) & ((x) << 4))
#define  MSCC_M_CPU_PCIE_INTR_INTR_PM_STATE             GENMASK(5,4)
#define  MSCC_X_CPU_PCIE_INTR_INTR_PM_STATE(x)          (((x) >> 4) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIE_INTR_INTR_LINK_AUTO_BW_STATUS(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_LINK_AUTO_BW_STATUS     BIT(3)
#define  MSCC_X_CPU_PCIE_INTR_INTR_LINK_AUTO_BW_STATUS(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_LINK_BW_MGT_STATUS(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_LINK_BW_MGT_STATUS     BIT(2)
#define  MSCC_X_CPU_PCIE_INTR_INTR_LINK_BW_MGT_STATUS(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_AER_RC_ERR_MSI(x)    ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_AER_RC_ERR_MSI       BIT(1)
#define  MSCC_X_CPU_PCIE_INTR_INTR_AER_RC_ERR_MSI(x)    ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_INTR_PME_MSI(x)           ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_INTR_INTR_PME_MSI              BIT(0)
#define  MSCC_X_CPU_PCIE_INTR_INTR_PME_MSI(x)           ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_INTR_ENA               MSCC_IOREG(MSCC_TO_CPU,0x5f)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_SYS_ERR_ENA(x)   ((x) ? BIT(10) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_SYS_ERR_ENA      BIT(10)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_SYS_ERR_ENA(x)   ((x) & BIT(10) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_EARLY_LINK_DOWN_ENA(x)  ((x) ? BIT(9) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_EARLY_LINK_DOWN_ENA     BIT(9)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_EARLY_LINK_DOWN_ENA(x)  ((x) & BIT(9) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_LTSSM_STATE_ENA(x)  ((x) ? BIT(8) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_LTSSM_STATE_ENA     BIT(8)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_LTSSM_STATE_ENA(x)  ((x) & BIT(8) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_LINK_STATE_ENA(x)  ((x) ? BIT(7) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_LINK_STATE_ENA     BIT(7)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_LINK_STATE_ENA(x)  ((x) & BIT(7) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_PM_STATE_ENA(x)  (GENMASK(6,5) & ((x) << 5))
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_PM_STATE_ENA     GENMASK(6,5)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_PM_STATE_ENA(x)  (((x) >> 5) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_LINK_AUTO_BW_ENA(x)  ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_LINK_AUTO_BW_ENA     BIT(4)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_LINK_AUTO_BW_ENA(x)  ((x) & BIT(4) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_LINK_BW_MGT_ENA(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_LINK_BW_MGT_ENA     BIT(3)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_LINK_BW_MGT_ENA(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_LINK_EQ_REQ_ENA(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_LINK_EQ_REQ_ENA     BIT(2)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_LINK_EQ_REQ_ENA(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_AER_RC_ERR_ENA(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_AER_RC_ERR_ENA     BIT(1)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_AER_RC_ERR_ENA(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_ENA_INTR_PME_ENA(x)       ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_INTR_ENA_INTR_PME_ENA          BIT(0)
#define  MSCC_X_CPU_PCIE_INTR_ENA_INTR_PME_ENA(x)       ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_INTR_IDENT             MSCC_IOREG(MSCC_TO_CPU,0x60)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_SYS_ERR_IDENT(x)  ((x) ? BIT(20) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_SYS_ERR_IDENT     BIT(20)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_SYS_ERR_IDENT(x)  ((x) & BIT(20) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_EARLY_LINK_DOWN_IDENT(x)  ((x) ? BIT(19) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_EARLY_LINK_DOWN_IDENT     BIT(19)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_EARLY_LINK_DOWN_IDENT(x)  ((x) & BIT(19) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_LTSSM_STATE_IDENT(x)  ((x) ? BIT(18) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_LTSSM_STATE_IDENT     BIT(18)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_LTSSM_STATE_IDENT(x)  ((x) & BIT(18) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_LINK_STATE_IDENT(x)  ((x) ? BIT(17) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_LINK_STATE_IDENT     BIT(17)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_LINK_STATE_IDENT(x)  ((x) & BIT(17) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_PM_STATE_IDENT(x)  (GENMASK(16,15) & ((x) << 15))
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_PM_STATE_IDENT     GENMASK(16,15)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_PM_STATE_IDENT(x)  (((x) >> 15) & GENMASK(1,0))
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_LINK_AUTO_BW_IDENT(x)  ((x) ? BIT(14) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_LINK_AUTO_BW_IDENT     BIT(14)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_LINK_AUTO_BW_IDENT(x)  ((x) & BIT(14) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_LINK_BW_MGT_IDENT(x)  ((x) ? BIT(13) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_LINK_BW_MGT_IDENT     BIT(13)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_LINK_BW_MGT_IDENT(x)  ((x) & BIT(13) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_LINK_EQ_REQ_IDENT(x)  ((x) ? BIT(12) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_LINK_EQ_REQ_IDENT     BIT(12)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_LINK_EQ_REQ_IDENT(x)  ((x) & BIT(12) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_AER_RC_ERR_IDENT(x)  ((x) ? BIT(11) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_AER_RC_ERR_IDENT     BIT(11)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_AER_RC_ERR_IDENT(x)  ((x) & BIT(11) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_AER_MSG_NUM(x)  (GENMASK(10,6) & ((x) << 6))
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_AER_MSG_NUM     GENMASK(10,6)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_AER_MSG_NUM(x)  (((x) >> 6) & GENMASK(4,0))
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_PME_IDENT(x)   ((x) ? BIT(5) : 0)
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_PME_IDENT      BIT(5)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_PME_IDENT(x)   ((x) & BIT(5) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_IDENT_INTR_PCIE_CAP_MSG_NUM(x)  (GENMASK(4,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_INTR_IDENT_INTR_PCIE_CAP_MSG_NUM     GENMASK(4,0)
#define  MSCC_X_CPU_PCIE_INTR_IDENT_INTR_PCIE_CAP_MSG_NUM(x)  (((x) >> 0) & GENMASK(4,0))

#define MSCC_CPU_PCIE_MSIX_DBELL_LOW         MSCC_IOREG(MSCC_TO_CPU,0x61)
#define  MSCC_F_CPU_PCIE_MSIX_DBELL_LOW_MSIX_DBELL_ADDR_LOW(x)  (x)
#define  MSCC_M_CPU_PCIE_MSIX_DBELL_LOW_MSIX_DBELL_ADDR_LOW     0xffffffff
#define  MSCC_X_CPU_PCIE_MSIX_DBELL_LOW_MSIX_DBELL_ADDR_LOW(x)  (x)

#define MSCC_CPU_PCIE_MSIX_DBELL_HIGH        MSCC_IOREG(MSCC_TO_CPU,0x62)
#define  MSCC_F_CPU_PCIE_MSIX_DBELL_HIGH_MSIX_DBELL_ADDR_HIGH(x)  (GENMASK(3,0) & ((x) << 0))
#define  MSCC_M_CPU_PCIE_MSIX_DBELL_HIGH_MSIX_DBELL_ADDR_HIGH     GENMASK(3,0)
#define  MSCC_X_CPU_PCIE_MSIX_DBELL_HIGH_MSIX_DBELL_ADDR_HIGH(x)  (((x) >> 0) & GENMASK(3,0))

#define MSCC_CPU_PCIE_INTR_COMMON_CFG(ri)    MSCC_IOREG(MSCC_TO_CPU,0x63 + (ri))
#define  MSCC_F_CPU_PCIE_INTR_COMMON_CFG_WAKEUP_ON_INTR_DIS(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_PCIE_INTR_COMMON_CFG_WAKEUP_ON_INTR_DIS     BIT(3)
#define  MSCC_X_CPU_PCIE_INTR_COMMON_CFG_WAKEUP_ON_INTR_DIS(x)  ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_COMMON_CFG_LEGACY_MODE_INTR_SEL(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_PCIE_INTR_COMMON_CFG_LEGACY_MODE_INTR_SEL     BIT(2)
#define  MSCC_X_CPU_PCIE_INTR_COMMON_CFG_LEGACY_MODE_INTR_SEL(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_COMMON_CFG_PCIE_INTR_ENA(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_INTR_COMMON_CFG_PCIE_INTR_ENA     BIT(1)
#define  MSCC_X_CPU_PCIE_INTR_COMMON_CFG_PCIE_INTR_ENA(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_COMMON_CFG_MSIX_INTR_ENA(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_INTR_COMMON_CFG_MSIX_INTR_ENA     BIT(0)
#define  MSCC_X_CPU_PCIE_INTR_COMMON_CFG_MSIX_INTR_ENA(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_INTR_CFG(ri)           MSCC_IOREG(MSCC_TO_CPU,0x65 + (ri))
#define  MSCC_F_CPU_PCIE_INTR_CFG_FUNCTION_NUMBER(x)    (GENMASK(29,27) & ((x) << 27))
#define  MSCC_M_CPU_PCIE_INTR_CFG_FUNCTION_NUMBER       GENMASK(29,27)
#define  MSCC_X_CPU_PCIE_INTR_CFG_FUNCTION_NUMBER(x)    (((x) >> 27) & GENMASK(2,0))
#define  MSCC_F_CPU_PCIE_INTR_CFG_TRAFFIC_CLASS(x)      (GENMASK(26,24) & ((x) << 24))
#define  MSCC_M_CPU_PCIE_INTR_CFG_TRAFFIC_CLASS         GENMASK(26,24)
#define  MSCC_X_CPU_PCIE_INTR_CFG_TRAFFIC_CLASS(x)      (((x) >> 24) & GENMASK(2,0))
#define  MSCC_F_CPU_PCIE_INTR_CFG_FALLING_VECTOR_VAL(x)  (GENMASK(23,13) & ((x) << 13))
#define  MSCC_M_CPU_PCIE_INTR_CFG_FALLING_VECTOR_VAL     GENMASK(23,13)
#define  MSCC_X_CPU_PCIE_INTR_CFG_FALLING_VECTOR_VAL(x)  (((x) >> 13) & GENMASK(10,0))
#define  MSCC_F_CPU_PCIE_INTR_CFG_RISING_VECTOR_VAL(x)  (GENMASK(12,2) & ((x) << 2))
#define  MSCC_M_CPU_PCIE_INTR_CFG_RISING_VECTOR_VAL     GENMASK(12,2)
#define  MSCC_X_CPU_PCIE_INTR_CFG_RISING_VECTOR_VAL(x)  (((x) >> 2) & GENMASK(10,0))
#define  MSCC_F_CPU_PCIE_INTR_CFG_INTR_FALLING_ENA(x)   ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_INTR_CFG_INTR_FALLING_ENA      BIT(1)
#define  MSCC_X_CPU_PCIE_INTR_CFG_INTR_FALLING_ENA(x)   ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_CFG_INTR_RISING_ENA(x)    ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_INTR_CFG_INTR_RISING_ENA       BIT(0)
#define  MSCC_X_CPU_PCIE_INTR_CFG_INTR_RISING_ENA(x)    ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_PCIE_INTR_STAT(ri)          MSCC_IOREG(MSCC_TO_CPU,0x67 + (ri))
#define  MSCC_F_CPU_PCIE_INTR_STAT_INTR_PENDING_FALLING(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_PCIE_INTR_STAT_INTR_PENDING_FALLING     BIT(1)
#define  MSCC_X_CPU_PCIE_INTR_STAT_INTR_PENDING_FALLING(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_PCIE_INTR_STAT_INTR_PENDING_RISING(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_PCIE_INTR_STAT_INTR_PENDING_RISING     BIT(0)
#define  MSCC_X_CPU_PCIE_INTR_STAT_INTR_PENDING_RISING(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_INTR_RAW                    MSCC_IOREG(MSCC_TO_CPU,0x69)
#define  MSCC_F_CPU_INTR_RAW_INTR_RAW(x)                (x)
#define  MSCC_M_CPU_INTR_RAW_INTR_RAW                   0xffffffff
#define  MSCC_X_CPU_INTR_RAW_INTR_RAW(x)                (x)

#define MSCC_CPU_INTR_RAW1                   MSCC_IOREG(MSCC_TO_CPU,0x6a)
#define  MSCC_F_CPU_INTR_RAW1_INTR_RAW1(x)              (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_RAW1_INTR_RAW1                 GENMASK(17,0)
#define  MSCC_X_CPU_INTR_RAW1_INTR_RAW1(x)              (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_TRIGGER(ri)            MSCC_IOREG(MSCC_TO_CPU,0x6b + (ri))
#define  MSCC_F_CPU_INTR_TRIGGER_INTR_TRIGGER(x)        (x)
#define  MSCC_M_CPU_INTR_TRIGGER_INTR_TRIGGER           0xffffffff
#define  MSCC_X_CPU_INTR_TRIGGER_INTR_TRIGGER(x)        (x)

#define MSCC_CPU_INTR_TRIGGER1(ri)           MSCC_IOREG(MSCC_TO_CPU,0x6d + (ri))
#define  MSCC_F_CPU_INTR_TRIGGER1_INTR_TRIGGER1(x)      (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_TRIGGER1_INTR_TRIGGER1         GENMASK(17,0)
#define  MSCC_X_CPU_INTR_TRIGGER1_INTR_TRIGGER1(x)      (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_FORCE                  MSCC_IOREG(MSCC_TO_CPU,0x6f)
#define  MSCC_F_CPU_INTR_FORCE_INTR_FORCE(x)            (x)
#define  MSCC_M_CPU_INTR_FORCE_INTR_FORCE               0xffffffff
#define  MSCC_X_CPU_INTR_FORCE_INTR_FORCE(x)            (x)

#define MSCC_CPU_INTR_FORCE1                 MSCC_IOREG(MSCC_TO_CPU,0x70)
#define  MSCC_F_CPU_INTR_FORCE1_INTR_FORCE1(x)          (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_FORCE1_INTR_FORCE1             GENMASK(17,0)
#define  MSCC_X_CPU_INTR_FORCE1_INTR_FORCE1(x)          (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_STICKY                 MSCC_IOREG(MSCC_TO_CPU,0x71)
#define  MSCC_F_CPU_INTR_STICKY_INTR_STICKY(x)          (x)
#define  MSCC_M_CPU_INTR_STICKY_INTR_STICKY             0xffffffff
#define  MSCC_X_CPU_INTR_STICKY_INTR_STICKY(x)          (x)

#define MSCC_CPU_INTR_STICKY1                MSCC_IOREG(MSCC_TO_CPU,0x72)
#define  MSCC_F_CPU_INTR_STICKY1_INTR_STICKY1(x)        (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_STICKY1_INTR_STICKY1           GENMASK(17,0)
#define  MSCC_X_CPU_INTR_STICKY1_INTR_STICKY1(x)        (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_BYPASS                 MSCC_IOREG(MSCC_TO_CPU,0x73)
#define  MSCC_F_CPU_INTR_BYPASS_INTR_BYPASS(x)          (x)
#define  MSCC_M_CPU_INTR_BYPASS_INTR_BYPASS             0xffffffff
#define  MSCC_X_CPU_INTR_BYPASS_INTR_BYPASS(x)          (x)

#define MSCC_CPU_INTR_BYPASS1                MSCC_IOREG(MSCC_TO_CPU,0x74)
#define  MSCC_F_CPU_INTR_BYPASS1_INTR_BYPASS1(x)        (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_BYPASS1_INTR_BYPASS1           GENMASK(17,0)
#define  MSCC_X_CPU_INTR_BYPASS1_INTR_BYPASS1(x)        (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_ENA                    MSCC_IOREG(MSCC_TO_CPU,0x75)
#define  MSCC_F_CPU_INTR_ENA_INTR_ENA(x)                (x)
#define  MSCC_M_CPU_INTR_ENA_INTR_ENA                   0xffffffff
#define  MSCC_X_CPU_INTR_ENA_INTR_ENA(x)                (x)

#define MSCC_CPU_INTR_ENA1                   MSCC_IOREG(MSCC_TO_CPU,0x76)
#define  MSCC_F_CPU_INTR_ENA1_INTR_ENA1(x)              (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_ENA1_INTR_ENA1                 GENMASK(17,0)
#define  MSCC_X_CPU_INTR_ENA1_INTR_ENA1(x)              (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_ENA_CLR                MSCC_IOREG(MSCC_TO_CPU,0x77)
#define  MSCC_F_CPU_INTR_ENA_CLR_INTR_ENA_CLR(x)        (x)
#define  MSCC_M_CPU_INTR_ENA_CLR_INTR_ENA_CLR           0xffffffff
#define  MSCC_X_CPU_INTR_ENA_CLR_INTR_ENA_CLR(x)        (x)

#define MSCC_CPU_INTR_ENA_CLR1               MSCC_IOREG(MSCC_TO_CPU,0x78)
#define  MSCC_F_CPU_INTR_ENA_CLR1_INTR_ENA_CLR1(x)      (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_ENA_CLR1_INTR_ENA_CLR1         GENMASK(17,0)
#define  MSCC_X_CPU_INTR_ENA_CLR1_INTR_ENA_CLR1(x)      (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_ENA_SET                MSCC_IOREG(MSCC_TO_CPU,0x79)
#define  MSCC_F_CPU_INTR_ENA_SET_INTR_ENA_SET(x)        (x)
#define  MSCC_M_CPU_INTR_ENA_SET_INTR_ENA_SET           0xffffffff
#define  MSCC_X_CPU_INTR_ENA_SET_INTR_ENA_SET(x)        (x)

#define MSCC_CPU_INTR_ENA_SET1               MSCC_IOREG(MSCC_TO_CPU,0x7a)
#define  MSCC_F_CPU_INTR_ENA_SET1_INTR_ENA_SET1(x)      (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_ENA_SET1_INTR_ENA_SET1         GENMASK(17,0)
#define  MSCC_X_CPU_INTR_ENA_SET1_INTR_ENA_SET1(x)      (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_INTR_IDENT                  MSCC_IOREG(MSCC_TO_CPU,0x7b)
#define  MSCC_F_CPU_INTR_IDENT_INTR_IDENT(x)            (x)
#define  MSCC_M_CPU_INTR_IDENT_INTR_IDENT               0xffffffff
#define  MSCC_X_CPU_INTR_IDENT_INTR_IDENT(x)            (x)

#define MSCC_CPU_INTR_IDENT1                 MSCC_IOREG(MSCC_TO_CPU,0x7c)
#define  MSCC_F_CPU_INTR_IDENT1_INTR_IDENT1(x)          (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_INTR_IDENT1_INTR_IDENT1             GENMASK(17,0)
#define  MSCC_X_CPU_INTR_IDENT1_INTR_IDENT1(x)          (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_DST_INTR_MAP(ri)            MSCC_IOREG(MSCC_TO_CPU,0x7d + (ri))
#define  MSCC_F_CPU_DST_INTR_MAP_DST_INTR_MAP(x)        (x)
#define  MSCC_M_CPU_DST_INTR_MAP_DST_INTR_MAP           0xffffffff
#define  MSCC_X_CPU_DST_INTR_MAP_DST_INTR_MAP(x)        (x)

#define MSCC_CPU_DST_INTR_MAP1(ri)           MSCC_IOREG(MSCC_TO_CPU,0x7f + (ri))
#define  MSCC_F_CPU_DST_INTR_MAP1_DST_INTR_MAP1(x)      (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_DST_INTR_MAP1_DST_INTR_MAP1         GENMASK(17,0)
#define  MSCC_X_CPU_DST_INTR_MAP1_DST_INTR_MAP1(x)      (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_DST_INTR_IDENT(ri)          MSCC_IOREG(MSCC_TO_CPU,0x81 + (ri))
#define  MSCC_F_CPU_DST_INTR_IDENT_DST_INTR_IDENT(x)    (x)
#define  MSCC_M_CPU_DST_INTR_IDENT_DST_INTR_IDENT       0xffffffff
#define  MSCC_X_CPU_DST_INTR_IDENT_DST_INTR_IDENT(x)    (x)

#define MSCC_CPU_DST_INTR_IDENT1(ri)         MSCC_IOREG(MSCC_TO_CPU,0x83 + (ri))
#define  MSCC_F_CPU_DST_INTR_IDENT1_DST_INTR_IDENT1(x)  (GENMASK(17,0) & ((x) << 0))
#define  MSCC_M_CPU_DST_INTR_IDENT1_DST_INTR_IDENT1     GENMASK(17,0)
#define  MSCC_X_CPU_DST_INTR_IDENT1_DST_INTR_IDENT1(x)  (((x) >> 0) & GENMASK(17,0))

#define MSCC_CPU_EXT_SRC_INTR_POL            MSCC_IOREG(MSCC_TO_CPU,0x85)
#define  MSCC_F_CPU_EXT_SRC_INTR_POL_EXT_SRC_INTR_POL(x)  (GENMASK(1,0) & ((x) << 0))
#define  MSCC_M_CPU_EXT_SRC_INTR_POL_EXT_SRC_INTR_POL     GENMASK(1,0)
#define  MSCC_X_CPU_EXT_SRC_INTR_POL_EXT_SRC_INTR_POL(x)  (((x) >> 0) & GENMASK(1,0))

#define MSCC_CPU_EXT_DST_INTR_POL            MSCC_IOREG(MSCC_TO_CPU,0x86)
#define  MSCC_F_CPU_EXT_DST_INTR_POL_EXT_DST_INTR_POL(x)  (GENMASK(1,0) & ((x) << 0))
#define  MSCC_M_CPU_EXT_DST_INTR_POL_EXT_DST_INTR_POL     GENMASK(1,0)
#define  MSCC_X_CPU_EXT_DST_INTR_POL_EXT_DST_INTR_POL(x)  (((x) >> 0) & GENMASK(1,0))

#define MSCC_CPU_EXT_DST_INTR_DRV            MSCC_IOREG(MSCC_TO_CPU,0x87)
#define  MSCC_F_CPU_EXT_DST_INTR_DRV_EXT_DST_INTR_DRV(x)  (GENMASK(1,0) & ((x) << 0))
#define  MSCC_M_CPU_EXT_DST_INTR_DRV_EXT_DST_INTR_DRV     GENMASK(1,0)
#define  MSCC_X_CPU_EXT_DST_INTR_DRV_EXT_DST_INTR_DRV(x)  (((x) >> 0) & GENMASK(1,0))

#define MSCC_CPU_DEV_INTR_POL                MSCC_IOREG(MSCC_TO_CPU,0x88)
#define  MSCC_F_CPU_DEV_INTR_POL_DEV_INTR_POL(x)        (x)
#define  MSCC_M_CPU_DEV_INTR_POL_DEV_INTR_POL           0xffffffff
#define  MSCC_X_CPU_DEV_INTR_POL_DEV_INTR_POL(x)        (x)

#define MSCC_CPU_DEV_INTR_POL1               MSCC_IOREG(MSCC_TO_CPU,0x89)
#define  MSCC_F_CPU_DEV_INTR_POL1_DEV_INTR_POL1(x)      (x)
#define  MSCC_M_CPU_DEV_INTR_POL1_DEV_INTR_POL1         0xffffffff
#define  MSCC_X_CPU_DEV_INTR_POL1_DEV_INTR_POL1(x)      (x)

#define MSCC_CPU_DEV_INTR_POL2               MSCC_IOREG(MSCC_TO_CPU,0x8a)
#define  MSCC_F_CPU_DEV_INTR_POL2_DEV_INTR_POL2(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_POL2_DEV_INTR_POL2         BIT(0)
#define  MSCC_X_CPU_DEV_INTR_POL2_DEV_INTR_POL2(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_RAW                MSCC_IOREG(MSCC_TO_CPU,0x8b)
#define  MSCC_F_CPU_DEV_INTR_RAW_DEV_INTR_RAW(x)        (x)
#define  MSCC_M_CPU_DEV_INTR_RAW_DEV_INTR_RAW           0xffffffff
#define  MSCC_X_CPU_DEV_INTR_RAW_DEV_INTR_RAW(x)        (x)

#define MSCC_CPU_DEV_INTR_RAW1               MSCC_IOREG(MSCC_TO_CPU,0x8c)
#define  MSCC_F_CPU_DEV_INTR_RAW1_DEV_INTR_RAW1(x)      (x)
#define  MSCC_M_CPU_DEV_INTR_RAW1_DEV_INTR_RAW1         0xffffffff
#define  MSCC_X_CPU_DEV_INTR_RAW1_DEV_INTR_RAW1(x)      (x)

#define MSCC_CPU_DEV_INTR_RAW2               MSCC_IOREG(MSCC_TO_CPU,0x8d)
#define  MSCC_F_CPU_DEV_INTR_RAW2_DEV_INTR_RAW2(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_RAW2_DEV_INTR_RAW2         BIT(0)
#define  MSCC_X_CPU_DEV_INTR_RAW2_DEV_INTR_RAW2(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_TRIGGER(ri)        MSCC_IOREG(MSCC_TO_CPU,0x8e + (ri))
#define  MSCC_F_CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER(x)  (x)

#define MSCC_CPU_DEV_INTR_TRIGGER1(ri)       MSCC_IOREG(MSCC_TO_CPU,0x90 + (ri))
#define  MSCC_F_CPU_DEV_INTR_TRIGGER1_DEV_INTR_TRIGGER1(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_TRIGGER1_DEV_INTR_TRIGGER1     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_TRIGGER1_DEV_INTR_TRIGGER1(x)  (x)

#define MSCC_CPU_DEV_INTR_TRIGGER2(ri)       MSCC_IOREG(MSCC_TO_CPU,0x92 + (ri))
#define  MSCC_F_CPU_DEV_INTR_TRIGGER2_DEV_INTR_TRIGGER2(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_TRIGGER2_DEV_INTR_TRIGGER2     BIT(0)
#define  MSCC_X_CPU_DEV_INTR_TRIGGER2_DEV_INTR_TRIGGER2(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_STICKY             MSCC_IOREG(MSCC_TO_CPU,0x94)
#define  MSCC_F_CPU_DEV_INTR_STICKY_DEV_INTR_STICKY(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_STICKY_DEV_INTR_STICKY     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_STICKY_DEV_INTR_STICKY(x)  (x)

#define MSCC_CPU_DEV_INTR_STICKY1            MSCC_IOREG(MSCC_TO_CPU,0x95)
#define  MSCC_F_CPU_DEV_INTR_STICKY1_DEV_INTR_STICKY1(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_STICKY1_DEV_INTR_STICKY1     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_STICKY1_DEV_INTR_STICKY1(x)  (x)

#define MSCC_CPU_DEV_INTR_STICKY2            MSCC_IOREG(MSCC_TO_CPU,0x96)
#define  MSCC_F_CPU_DEV_INTR_STICKY2_DEV_INTR_STICKY2(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_STICKY2_DEV_INTR_STICKY2     BIT(0)
#define  MSCC_X_CPU_DEV_INTR_STICKY2_DEV_INTR_STICKY2(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_BYPASS             MSCC_IOREG(MSCC_TO_CPU,0x97)
#define  MSCC_F_CPU_DEV_INTR_BYPASS_DEV_INTR_BYPASS(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_BYPASS_DEV_INTR_BYPASS     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_BYPASS_DEV_INTR_BYPASS(x)  (x)

#define MSCC_CPU_DEV_INTR_BYPASS1            MSCC_IOREG(MSCC_TO_CPU,0x98)
#define  MSCC_F_CPU_DEV_INTR_BYPASS1_DEV_INTR_BYPASS1(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_BYPASS1_DEV_INTR_BYPASS1     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_BYPASS1_DEV_INTR_BYPASS1(x)  (x)

#define MSCC_CPU_DEV_INTR_BYPASS2            MSCC_IOREG(MSCC_TO_CPU,0x99)
#define  MSCC_F_CPU_DEV_INTR_BYPASS2_DEV_INTR_BYPASS2(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_BYPASS2_DEV_INTR_BYPASS2     BIT(0)
#define  MSCC_X_CPU_DEV_INTR_BYPASS2_DEV_INTR_BYPASS2(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_ENA                MSCC_IOREG(MSCC_TO_CPU,0x9a)
#define  MSCC_F_CPU_DEV_INTR_ENA_DEV_INTR_ENA(x)        (x)
#define  MSCC_M_CPU_DEV_INTR_ENA_DEV_INTR_ENA           0xffffffff
#define  MSCC_X_CPU_DEV_INTR_ENA_DEV_INTR_ENA(x)        (x)

#define MSCC_CPU_DEV_INTR_ENA1               MSCC_IOREG(MSCC_TO_CPU,0x9b)
#define  MSCC_F_CPU_DEV_INTR_ENA1_DEV_INTR_ENA1(x)      (x)
#define  MSCC_M_CPU_DEV_INTR_ENA1_DEV_INTR_ENA1         0xffffffff
#define  MSCC_X_CPU_DEV_INTR_ENA1_DEV_INTR_ENA1(x)      (x)

#define MSCC_CPU_DEV_INTR_ENA2               MSCC_IOREG(MSCC_TO_CPU,0x9c)
#define  MSCC_F_CPU_DEV_INTR_ENA2_DEV_INTR_ENA2(x)      ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_ENA2_DEV_INTR_ENA2         BIT(0)
#define  MSCC_X_CPU_DEV_INTR_ENA2_DEV_INTR_ENA2(x)      ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_DEV_INTR_IDENT              MSCC_IOREG(MSCC_TO_CPU,0x9d)
#define  MSCC_F_CPU_DEV_INTR_IDENT_DEV_INTR_IDENT(x)    (x)
#define  MSCC_M_CPU_DEV_INTR_IDENT_DEV_INTR_IDENT       0xffffffff
#define  MSCC_X_CPU_DEV_INTR_IDENT_DEV_INTR_IDENT(x)    (x)

#define MSCC_CPU_DEV_INTR_IDENT1             MSCC_IOREG(MSCC_TO_CPU,0x9e)
#define  MSCC_F_CPU_DEV_INTR_IDENT1_DEV_INTR_IDENT1(x)  (x)
#define  MSCC_M_CPU_DEV_INTR_IDENT1_DEV_INTR_IDENT1     0xffffffff
#define  MSCC_X_CPU_DEV_INTR_IDENT1_DEV_INTR_IDENT1(x)  (x)

#define MSCC_CPU_DEV_INTR_IDENT2             MSCC_IOREG(MSCC_TO_CPU,0x9f)
#define  MSCC_F_CPU_DEV_INTR_IDENT2_DEV_INTR_IDENT2(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DEV_INTR_IDENT2_DEV_INTR_IDENT2     BIT(0)
#define  MSCC_X_CPU_DEV_INTR_IDENT2_DEV_INTR_IDENT2(x)  ((x) & BIT(0) ? 1 : 0)

#define MSCC_CPU_KR6G_INTR_POL               MSCC_IOREG(MSCC_TO_CPU,0xa0)
#define  MSCC_F_CPU_KR6G_INTR_POL_KR6G_INTR_POL(x)      (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_POL_KR6G_INTR_POL         GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_POL_KR6G_INTR_POL(x)      (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_RAW               MSCC_IOREG(MSCC_TO_CPU,0xa1)
#define  MSCC_F_CPU_KR6G_INTR_RAW_KR6G_INTR_RAW(x)      (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_RAW_KR6G_INTR_RAW         GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_RAW_KR6G_INTR_RAW(x)      (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_TRIGGER(ri)       MSCC_IOREG(MSCC_TO_CPU,0xa2 + (ri))
#define  MSCC_F_CPU_KR6G_INTR_TRIGGER_KR6G_INTR_TRIGGER(x)  (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_TRIGGER_KR6G_INTR_TRIGGER     GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_TRIGGER_KR6G_INTR_TRIGGER(x)  (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_STICKY            MSCC_IOREG(MSCC_TO_CPU,0xa4)
#define  MSCC_F_CPU_KR6G_INTR_STICKY_KR6G_INTR_STICKY(x)  (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_STICKY_KR6G_INTR_STICKY     GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_STICKY_KR6G_INTR_STICKY(x)  (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_BYPASS            MSCC_IOREG(MSCC_TO_CPU,0xa5)
#define  MSCC_F_CPU_KR6G_INTR_BYPASS_KR6G_INTR_BYPASS(x)  (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_BYPASS_KR6G_INTR_BYPASS     GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_BYPASS_KR6G_INTR_BYPASS(x)  (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_ENA               MSCC_IOREG(MSCC_TO_CPU,0xa6)
#define  MSCC_F_CPU_KR6G_INTR_ENA_KR6G_INTR_ENA(x)      (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_ENA_KR6G_INTR_ENA         GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_ENA_KR6G_INTR_ENA(x)      (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR6G_INTR_IDENT             MSCC_IOREG(MSCC_TO_CPU,0xa7)
#define  MSCC_F_CPU_KR6G_INTR_IDENT_KR6G_INTR_IDENT(x)  (GENMASK(12,0) & ((x) << 0))
#define  MSCC_M_CPU_KR6G_INTR_IDENT_KR6G_INTR_IDENT     GENMASK(12,0)
#define  MSCC_X_CPU_KR6G_INTR_IDENT_KR6G_INTR_IDENT(x)  (((x) >> 0) & GENMASK(12,0))

#define MSCC_CPU_KR10G_INTR_POL              MSCC_IOREG(MSCC_TO_CPU,0xa8)
#define  MSCC_F_CPU_KR10G_INTR_POL_KR10G_INTR_POL(x)    (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_POL_KR10G_INTR_POL       GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_POL_KR10G_INTR_POL(x)    (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_RAW              MSCC_IOREG(MSCC_TO_CPU,0xa9)
#define  MSCC_F_CPU_KR10G_INTR_RAW_KR10G_INTR_RAW(x)    (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_RAW_KR10G_INTR_RAW       GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_RAW_KR10G_INTR_RAW(x)    (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_TRIGGER(ri)      MSCC_IOREG(MSCC_TO_CPU,0xaa + (ri))
#define  MSCC_F_CPU_KR10G_INTR_TRIGGER_KR10G_INTR_TRIGGER(x)  (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_TRIGGER_KR10G_INTR_TRIGGER     GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_TRIGGER_KR10G_INTR_TRIGGER(x)  (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_STICKY           MSCC_IOREG(MSCC_TO_CPU,0xac)
#define  MSCC_F_CPU_KR10G_INTR_STICKY_KR10G_INTR_STICKY(x)  (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_STICKY_KR10G_INTR_STICKY     GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_STICKY_KR10G_INTR_STICKY(x)  (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_BYPASS           MSCC_IOREG(MSCC_TO_CPU,0xad)
#define  MSCC_F_CPU_KR10G_INTR_BYPASS_KR10G_INTR_BYPASS(x)  (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_BYPASS_KR10G_INTR_BYPASS     GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_BYPASS_KR10G_INTR_BYPASS(x)  (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_ENA              MSCC_IOREG(MSCC_TO_CPU,0xae)
#define  MSCC_F_CPU_KR10G_INTR_ENA_KR10G_INTR_ENA(x)    (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_ENA_KR10G_INTR_ENA       GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_ENA_KR10G_INTR_ENA(x)    (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_KR10G_INTR_IDENT            MSCC_IOREG(MSCC_TO_CPU,0xaf)
#define  MSCC_F_CPU_KR10G_INTR_IDENT_KR10G_INTR_IDENT(x)  (GENMASK(19,0) & ((x) << 0))
#define  MSCC_M_CPU_KR10G_INTR_IDENT_KR10G_INTR_IDENT     GENMASK(19,0)
#define  MSCC_X_CPU_KR10G_INTR_IDENT_KR10G_INTR_IDENT(x)  (((x) >> 0) & GENMASK(19,0))

#define MSCC_CPU_DDRCTRL_CLK                 MSCC_IOREG(MSCC_TO_CPU,0xb0)
#define  MSCC_F_CPU_DDRCTRL_CLK_DDR_CLK_ENA(x)          ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DDRCTRL_CLK_DDR_CLK_ENA             BIT(0)
#define  MSCC_X_CPU_DDRCTRL_CLK_DDR_CLK_ENA(x)          ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_CLK_DDR_AXI_CLK_ENA(x)      ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_DDRCTRL_CLK_DDR_AXI_CLK_ENA         BIT(1)
#define  MSCC_X_CPU_DDRCTRL_CLK_DDR_AXI_CLK_ENA(x)      ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_CLK_DDR_APB_CLK_ENA(x)      ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_DDRCTRL_CLK_DDR_APB_CLK_ENA         BIT(2)
#define  MSCC_X_CPU_DDRCTRL_CLK_DDR_APB_CLK_ENA(x)      ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_CLK_DDRPHY_CTL_CLK_ENA(x)   ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_DDRCTRL_CLK_DDRPHY_CTL_CLK_ENA      BIT(3)
#define  MSCC_X_CPU_DDRCTRL_CLK_DDRPHY_CTL_CLK_ENA(x)   ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_CLK_DDRPHY_APB_CLK_ENA(x)   ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_DDRCTRL_CLK_DDRPHY_APB_CLK_ENA      BIT(4)
#define  MSCC_X_CPU_DDRCTRL_CLK_DDRPHY_APB_CLK_ENA(x)   ((x) & BIT(4) ? 1 : 0)

#define MSCC_CPU_DDRCTRL_RST                 MSCC_IOREG(MSCC_TO_CPU,0xb1)
#define  MSCC_F_CPU_DDRCTRL_RST_DDRC_RST(x)             ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DDRCTRL_RST_DDRC_RST                BIT(0)
#define  MSCC_X_CPU_DDRCTRL_RST_DDRC_RST(x)             ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_RST_DDR_AXI_RST(x)          ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_DDRCTRL_RST_DDR_AXI_RST             BIT(1)
#define  MSCC_X_CPU_DDRCTRL_RST_DDR_AXI_RST(x)          ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_RST_DDR_APB_RST(x)          ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_DDRCTRL_RST_DDR_APB_RST             BIT(2)
#define  MSCC_X_CPU_DDRCTRL_RST_DDR_APB_RST(x)          ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_RST_DDRPHY_CTL_RST(x)       ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_DDRCTRL_RST_DDRPHY_CTL_RST          BIT(3)
#define  MSCC_X_CPU_DDRCTRL_RST_DDRPHY_CTL_RST(x)       ((x) & BIT(3) ? 1 : 0)
#define  MSCC_F_CPU_DDRCTRL_RST_DDRPHY_APB_RST(x)       ((x) ? BIT(4) : 0)
#define  MSCC_M_CPU_DDRCTRL_RST_DDRPHY_APB_RST          BIT(4)
#define  MSCC_X_CPU_DDRCTRL_RST_DDRPHY_APB_RST(x)       ((x) & BIT(4) ? 1 : 0)

#define MSCC_CPU_DDRC_INTR_RAW_STAT          MSCC_IOREG(MSCC_TO_CPU,0xb2)
#define  MSCC_F_CPU_DDRC_INTR_RAW_STAT_SBR_DONE_INTR_RAW_STAT(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DDRC_INTR_RAW_STAT_SBR_DONE_INTR_RAW_STAT     BIT(0)
#define  MSCC_X_CPU_DDRC_INTR_RAW_STAT_SBR_DONE_INTR_RAW_STAT(x)  ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_RAW_STAT_ECC_CORRECTED_ERR_INTR_RAW_STAT(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_DDRC_INTR_RAW_STAT_ECC_CORRECTED_ERR_INTR_RAW_STAT     BIT(1)
#define  MSCC_X_CPU_DDRC_INTR_RAW_STAT_ECC_CORRECTED_ERR_INTR_RAW_STAT(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_RAW_STAT_ECC_UNCORRECTED_ERR_INTR_RAW_STAT(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_DDRC_INTR_RAW_STAT_ECC_UNCORRECTED_ERR_INTR_RAW_STAT     BIT(2)
#define  MSCC_X_CPU_DDRC_INTR_RAW_STAT_ECC_UNCORRECTED_ERR_INTR_RAW_STAT(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_RAW_STAT_DFI_ALERT_ERR_INTR_RAW_STAT(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_DDRC_INTR_RAW_STAT_DFI_ALERT_ERR_INTR_RAW_STAT     BIT(3)
#define  MSCC_X_CPU_DDRC_INTR_RAW_STAT_DFI_ALERT_ERR_INTR_RAW_STAT(x)  ((x) & BIT(3) ? 1 : 0)

#define MSCC_CPU_DDRC_INTR_MASK              MSCC_IOREG(MSCC_TO_CPU,0xb3)
#define  MSCC_F_CPU_DDRC_INTR_MASK_SBR_DONE_INTR_MASK(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASK_SBR_DONE_INTR_MASK     BIT(0)
#define  MSCC_X_CPU_DDRC_INTR_MASK_SBR_DONE_INTR_MASK(x)  ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASK_ECC_CORRECTED_ERR_INTR_MASK(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASK_ECC_CORRECTED_ERR_INTR_MASK     BIT(1)
#define  MSCC_X_CPU_DDRC_INTR_MASK_ECC_CORRECTED_ERR_INTR_MASK(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASK_ECC_UNCORRECTED_ERR_INTR_MASK(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASK_ECC_UNCORRECTED_ERR_INTR_MASK     BIT(2)
#define  MSCC_X_CPU_DDRC_INTR_MASK_ECC_UNCORRECTED_ERR_INTR_MASK(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASK_DFI_ALERT_ERR_INTR_MASK(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASK_DFI_ALERT_ERR_INTR_MASK     BIT(3)
#define  MSCC_X_CPU_DDRC_INTR_MASK_DFI_ALERT_ERR_INTR_MASK(x)  ((x) & BIT(3) ? 1 : 0)

#define MSCC_CPU_DDRC_INTR_MASKED_STAT       MSCC_IOREG(MSCC_TO_CPU,0xb4)
#define  MSCC_F_CPU_DDRC_INTR_MASKED_STAT_SBR_DONE_INTR_STAT(x)  ((x) ? BIT(0) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASKED_STAT_SBR_DONE_INTR_STAT     BIT(0)
#define  MSCC_X_CPU_DDRC_INTR_MASKED_STAT_SBR_DONE_INTR_STAT(x)  ((x) & BIT(0) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASKED_STAT_ECC_CORRECTED_ERR_INTR_STAT(x)  ((x) ? BIT(1) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASKED_STAT_ECC_CORRECTED_ERR_INTR_STAT     BIT(1)
#define  MSCC_X_CPU_DDRC_INTR_MASKED_STAT_ECC_CORRECTED_ERR_INTR_STAT(x)  ((x) & BIT(1) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASKED_STAT_ECC_UNCORRECTED_ERR_INTR_STAT(x)  ((x) ? BIT(2) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASKED_STAT_ECC_UNCORRECTED_ERR_INTR_STAT     BIT(2)
#define  MSCC_X_CPU_DDRC_INTR_MASKED_STAT_ECC_UNCORRECTED_ERR_INTR_STAT(x)  ((x) & BIT(2) ? 1 : 0)
#define  MSCC_F_CPU_DDRC_INTR_MASKED_STAT_DFI_ALERT_ERR_INTR_STAT(x)  ((x) ? BIT(3) : 0)
#define  MSCC_M_CPU_DDRC_INTR_MASKED_STAT_DFI_ALERT_ERR_INTR_STAT     BIT(3)
#define  MSCC_X_CPU_DDRC_INTR_MASKED_STAT_DFI_ALERT_ERR_INTR_STAT(x)  ((x) & BIT(3) ? 1 : 0)


#endif /* _MSCC_FA_REGS_CPU_H_ */
