// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 Microsemi Corporation
 */

//#define DEBUG

#include <common.h>
#include <asm/io.h>

#include <dt-bindings/mscc/fireant_data.h>
#include "fireant_serdes.h"

/* Generation Tag is temp */

/* ================================================================= *
 *               Note: This code is autogenerated from the
 *                     Universal Tcl Environment (UTE) which provides
 *                     consistent setup functions for
 *       ^             - Verification
 *      / \            - Validation
 *     /   \           - Test Pattern Generation and
 *    /  |  \          - Software
 *   /   !   \         It should not be modified manually.
 *  /_________\        In case there is a need for modifications,
 *                     please contact
 *                       Srinivas Bandari <srinivas.bandari@microchip.com>
 * ================================================================= */

static vtss_rc  vtss_ant_sd10g28_cmu_reg_cfg(u32 cmu_num)
{
    vtss_rc rc = VTSS_RC_OK;
    u32 value;
    void *cmu_tgt = VTSS_TO_SD_CMU(cmu_num);
    void *cmu_cfg_tgt = VTSS_TO_SD_CMU_CFG(cmu_num);
    u32 spd10g = 1;

    if (cmu_num == 1 || cmu_num == 4 || cmu_num == 7 || cmu_num == 10 || cmu_num == 13) {
        spd10g = 0;
    }

    REG_WRM(VTSS_SD_CMU_TERM_TARGET_SD_CMU_CFG(cmu_cfg_tgt),
                VTSS_F_SD_CMU_TERM_TARGET_SD_CMU_CFG_EXT_CFG_RST(1),
                VTSS_M_SD_CMU_TERM_TARGET_SD_CMU_CFG_EXT_CFG_RST);

    REG_WRM(VTSS_SD_CMU_TERM_TARGET_SD_CMU_CFG(cmu_cfg_tgt),
                VTSS_F_SD_CMU_TERM_TARGET_SD_CMU_CFG_EXT_CFG_RST(0),
                VTSS_M_SD_CMU_TERM_TARGET_SD_CMU_CFG_EXT_CFG_RST);

    REG_WRM(VTSS_SD_CMU_TERM_TARGET_SD_CMU_CFG(cmu_cfg_tgt),
                VTSS_F_SD_CMU_TERM_TARGET_SD_CMU_CFG_CMU_RST(1),
                VTSS_M_SD_CMU_TERM_TARGET_SD_CMU_CFG_CMU_RST);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_45(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_45_R_DWIDTHCTRL_FROM_HWT(0x1) |
        VTSS_F_SD10G_CMU_TARGET_CMU_45_R_REFCK_SSC_EN_FROM_HWT(0x1) |
        VTSS_F_SD10G_CMU_TARGET_CMU_45_R_LINK_BUF_EN_FROM_HWT(0x1) |
        VTSS_F_SD10G_CMU_TARGET_CMU_45_R_BIAS_EN_FROM_HWT(0x1) |
        VTSS_F_SD10G_CMU_TARGET_CMU_45_R_EN_RATECHG_CTRL(0x0),
                VTSS_M_SD10G_CMU_TARGET_CMU_45_R_DWIDTHCTRL_FROM_HWT |
        VTSS_M_SD10G_CMU_TARGET_CMU_45_R_REFCK_SSC_EN_FROM_HWT |
        VTSS_M_SD10G_CMU_TARGET_CMU_45_R_LINK_BUF_EN_FROM_HWT |
        VTSS_M_SD10G_CMU_TARGET_CMU_45_R_BIAS_EN_FROM_HWT |
        VTSS_M_SD10G_CMU_TARGET_CMU_45_R_EN_RATECHG_CTRL);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_47(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_47_R_PCS2PMA_PHYMODE_4_0(0),
                VTSS_M_SD10G_CMU_TARGET_CMU_47_R_PCS2PMA_PHYMODE_4_0);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_1B(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_1B_CFG_RESERVE_7_0(0),
                VTSS_M_SD10G_CMU_TARGET_CMU_1B_CFG_RESERVE_7_0);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_0D(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_0D_CFG_JC_BYP(0x1),
                VTSS_M_SD10G_CMU_TARGET_CMU_0D_CFG_JC_BYP);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_1F(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_1F_CFG_VTUNE_SEL(1),
                VTSS_M_SD10G_CMU_TARGET_CMU_1F_CFG_VTUNE_SEL);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_00(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_00_CFG_PLL_TP_SEL_1_0(3),
                VTSS_M_SD10G_CMU_TARGET_CMU_00_CFG_PLL_TP_SEL_1_0);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_05(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_05_CFG_BIAS_TP_SEL_1_0(3),
                VTSS_M_SD10G_CMU_TARGET_CMU_05_CFG_BIAS_TP_SEL_1_0);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_30(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_30_R_PLL_DLOL_EN(1),
                VTSS_M_SD10G_CMU_TARGET_CMU_30_R_PLL_DLOL_EN);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_09(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_09_CFG_SW_10G(spd10g),
                VTSS_M_SD10G_CMU_TARGET_CMU_09_CFG_SW_10G);

    REG_WRM(VTSS_SD_CMU_TERM_TARGET_SD_CMU_CFG(cmu_cfg_tgt),
                VTSS_F_SD_CMU_TERM_TARGET_SD_CMU_CFG_CMU_RST(0),
                VTSS_M_SD_CMU_TERM_TARGET_SD_CMU_CFG_CMU_RST);

    VTSS_MSLEEP(20);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_44(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_44_R_PLL_RSTN(0),
                VTSS_M_SD10G_CMU_TARGET_CMU_44_R_PLL_RSTN);

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_44(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_44_R_PLL_RSTN(1),
                VTSS_M_SD10G_CMU_TARGET_CMU_44_R_PLL_RSTN);

    VTSS_MSLEEP(20);

    REG_RD(VTSS_SD10G_CMU_TARGET_CMU_E0(cmu_tgt), &value);
    value = VTSS_X_SD10G_CMU_TARGET_CMU_E0_PLL_LOL_UDL(value);
    value = (value > 0) ? 1 : 0;
    if(value != 0x0) {
        VTSS_E("CMU:%d The expected value for CMU_E0 pll_lol_udl was 0x0 but is 0x%x\n",cmu_num, value);
        rc = VTSS_RC_ERROR;
    } else {
        VTSS_D("Note: The value of CMU_E0 pll_lol_udl was 0x%x\n", value);
    }

    REG_WRM(VTSS_SD10G_CMU_TARGET_CMU_0D(cmu_tgt),
                VTSS_F_SD10G_CMU_TARGET_CMU_0D_CFG_PMA_TX_CK_PD(0),
                VTSS_M_SD10G_CMU_TARGET_CMU_0D_CFG_PMA_TX_CK_PD);


  return rc;
}

static vtss_rc  vtss_ant_sd10g28_reg_cfg(vtss_sd10g28_setup_struct_t *res_struct,
					 vtss_port_no_t port_no,
					 u32 sd_type,
					 u32 indx)
{
    vtss_rc rc = VTSS_RC_OK;
    u32 value;
    void *sd_lane_tgt;
    void *sd_tgt;

    //cmu_num = vtss_fa_sd10g28_get_cmu(vtss_state, res_struct->cmu_sel[0],port_no);
    //vtss_ant_sd10g28_cmu_reg_cfg(cmu_num);

    if(sd_type == FA_SERDES_TYPE_6G) {
        sd_tgt = VTSS_TO_SD6G_LANE(indx);
        sd_lane_tgt = VTSS_TO_SD_LANE(indx);
    } else {
        sd_tgt = VTSS_TO_SD10G_LANE(indx);
        sd_lane_tgt = VTSS_TO_SD_LANE(indx+VTSS_SERDES_10G_START);
    }

/* Note: SerDes SD10G_LANE_1 is configured in 10G_LAN mode */
    REG_WRM(VTSS_SD_LANE_TARGET_SD_LANE_CFG(sd_lane_tgt),
                VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_EXT_CFG_RST(1),
                VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_EXT_CFG_RST);

    VTSS_MSLEEP(1);

    REG_WRM(VTSS_SD_LANE_TARGET_SD_LANE_CFG(sd_lane_tgt),
                VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_EXT_CFG_RST(0),
                VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_EXT_CFG_RST);

    REG_WRM(VTSS_SD_LANE_TARGET_SD_LANE_CFG(sd_lane_tgt),
                VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_MACRO_RST(1),
                VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_MACRO_RST);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_93(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_93_R_DWIDTHCTRL_FROM_HWT(0x0) |
        VTSS_F_SD10G_LANE_TARGET_LANE_93_R_REG_MANUAL(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_93_R_AUXCKSEL_FROM_HWT(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_93_R_LANE_ID_FROM_HWT(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_93_R_EN_RATECHG_CTRL(0x0),
                VTSS_M_SD10G_LANE_TARGET_LANE_93_R_DWIDTHCTRL_FROM_HWT |
        VTSS_M_SD10G_LANE_TARGET_LANE_93_R_REG_MANUAL |
        VTSS_M_SD10G_LANE_TARGET_LANE_93_R_AUXCKSEL_FROM_HWT |
        VTSS_M_SD10G_LANE_TARGET_LANE_93_R_LANE_ID_FROM_HWT |
        VTSS_M_SD10G_LANE_TARGET_LANE_93_R_EN_RATECHG_CTRL);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_94(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_94_R_ISCAN_REG(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_94_R_TXEQ_REG(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_94_R_MISC_REG(0x1) |
        VTSS_F_SD10G_LANE_TARGET_LANE_94_R_SWING_REG(0x1),
                VTSS_M_SD10G_LANE_TARGET_LANE_94_R_ISCAN_REG |
        VTSS_M_SD10G_LANE_TARGET_LANE_94_R_TXEQ_REG |
        VTSS_M_SD10G_LANE_TARGET_LANE_94_R_MISC_REG |
        VTSS_M_SD10G_LANE_TARGET_LANE_94_R_SWING_REG);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_9E(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_9E_R_RXEQ_REG(0x1),
                VTSS_M_SD10G_LANE_TARGET_LANE_9E_R_RXEQ_REG);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_A1(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_A1_R_SSC_FROM_HWT(0x0) |
        VTSS_F_SD10G_LANE_TARGET_LANE_A1_R_CDR_FROM_HWT(0x0) |
        VTSS_F_SD10G_LANE_TARGET_LANE_A1_R_PCLK_GATING_FROM_HWT(0x1),
                VTSS_M_SD10G_LANE_TARGET_LANE_A1_R_SSC_FROM_HWT |
        VTSS_M_SD10G_LANE_TARGET_LANE_A1_R_CDR_FROM_HWT |
        VTSS_M_SD10G_LANE_TARGET_LANE_A1_R_PCLK_GATING_FROM_HWT);

    REG_WRM(VTSS_SD_LANE_TARGET_SD_LANE_CFG(sd_lane_tgt),
                VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_RX_REF_SEL(res_struct->cmu_sel[0]) |
        VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_TX_REF_SEL(res_struct->cmu_sel[0]),
                VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_RX_REF_SEL |
        VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_TX_REF_SEL);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_40(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_40_CFG_LANE_RESERVE_7_0(res_struct->cfg_lane_reserve_7_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_40_CFG_LANE_RESERVE_7_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_50(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_50_CFG_SSC_RTL_CLK_SEL(res_struct->cfg_ssc_rtl_clk_sel[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_50_CFG_SSC_RTL_CLK_SEL);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_35(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_35_CFG_TXRATE_1_0(res_struct->cfg_txrate_1_0[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_35_CFG_RXRATE_1_0(res_struct->cfg_rxrate_1_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_35_CFG_TXRATE_1_0 |
        VTSS_M_SD10G_LANE_TARGET_LANE_35_CFG_RXRATE_1_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_94(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_94_R_DWIDTHCTRL_2_0(res_struct->r_DwidthCtrl_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_94_R_DWIDTHCTRL_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_01(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_01_CFG_PMA_TX_CK_BITWIDTH_2_0(res_struct->cfg_pma_tx_ck_bitwidth_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_01_CFG_PMA_TX_CK_BITWIDTH_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_30(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_30_CFG_RXDIV_SEL_2_0(res_struct->cfg_rxdiv_sel_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_30_CFG_RXDIV_SEL_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_A2(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_A2_R_PCS2PMA_PHYMODE_4_0(res_struct->r_pcs2pma_phymode_4_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_A2_R_PCS2PMA_PHYMODE_4_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_13(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_13_CFG_CDRCK_EN(res_struct->cfg_cdrck_en[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_13_CFG_CDRCK_EN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_23(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_23_CFG_DFECK_EN(res_struct->cfg_dfeck_en[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_23_CFG_DFE_PD(res_struct->cfg_dfe_pd[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_23_CFG_ERRAMP_PD(res_struct->cfg_erramp_pd[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_23_CFG_DFECK_EN |
        VTSS_M_SD10G_LANE_TARGET_LANE_23_CFG_DFE_PD |
        VTSS_M_SD10G_LANE_TARGET_LANE_23_CFG_ERRAMP_PD);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_22(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_22_CFG_DFETAP_EN_5_1(res_struct->cfg_dfetap_en_5_1[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_22_CFG_DFETAP_EN_5_1);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_1A(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_1A_CFG_PI_DFE_EN(res_struct->cfg_pi_DFE_en[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_1A_CFG_PI_DFE_EN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_02(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_02_CFG_EN_ADV(res_struct->cfg_en_adv[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_02_CFG_EN_MAIN(res_struct->cfg_en_main[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_02_CFG_EN_DLY(res_struct->cfg_en_dly[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_02_CFG_TAP_ADV_3_0(res_struct->cfg_tap_adv_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_02_CFG_EN_ADV |
        VTSS_M_SD10G_LANE_TARGET_LANE_02_CFG_EN_MAIN |
        VTSS_M_SD10G_LANE_TARGET_LANE_02_CFG_EN_DLY |
        VTSS_M_SD10G_LANE_TARGET_LANE_02_CFG_TAP_ADV_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_03(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_03_CFG_TAP_MAIN(res_struct->cfg_tap_main[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_03_CFG_TAP_MAIN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_04(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_04_CFG_TAP_DLY_4_0(res_struct->cfg_tap_dly_4_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_04_CFG_TAP_DLY_4_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_2F(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_2F_CFG_VGA_CTRL_3_0(res_struct->cfg_vga_ctrl_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_2F_CFG_VGA_CTRL_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_2F(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_2F_CFG_VGA_CP_2_0(res_struct->cfg_vga_cp_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_2F_CFG_VGA_CP_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0B(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0B_CFG_EQ_RES_3_0(res_struct->cfg_eq_res_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0B_CFG_EQ_RES_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0D(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0D_CFG_EQR_BYP(res_struct->cfg_eqR_byp[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0D_CFG_EQR_BYP);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0E(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0E_CFG_EQC_FORCE_3_0(res_struct->cfg_eqC_force_3_0[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_0E_CFG_SUM_SETCM_EN(res_struct->cfg_sum_setcm_en[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0E_CFG_EQC_FORCE_3_0 |
        VTSS_M_SD10G_LANE_TARGET_LANE_0E_CFG_SUM_SETCM_EN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_23(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_23_CFG_EN_DFEDIG(res_struct->cfg_en_dfedig[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_23_CFG_EN_DFEDIG);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_06(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_06_CFG_EN_PREEMPH(res_struct->cfg_en_preemph[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_06_CFG_EN_PREEMPH);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_33(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_33_CFG_ITX_IPPREEMP_BASE_1_0(res_struct->cfg_itx_ippreemp_base_1_0[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_33_CFG_ITX_IPDRIVER_BASE_2_0(res_struct->cfg_itx_ipdriver_base_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_33_CFG_ITX_IPPREEMP_BASE_1_0 |
        VTSS_M_SD10G_LANE_TARGET_LANE_33_CFG_ITX_IPDRIVER_BASE_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_52(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_52_CFG_IBIAS_TUNE_RESERVE_5_0(res_struct->cfg_ibias_tune_reserve_5_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_52_CFG_IBIAS_TUNE_RESERVE_5_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_37(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_37_CFG_TXSWING_HALF(res_struct->cfg_txswing_half[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_37_CFG_TXSWING_HALF);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_3C(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_3C_CFG_DIS_2NDORDER(res_struct->cfg_dis_2ndOrder[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_3C_CFG_DIS_2NDORDER);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_39(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_39_CFG_RX_SSC_LH(res_struct->cfg_rx_ssc_lh[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_39_CFG_RX_SSC_LH);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_1A(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_1A_CFG_PI_FLOOP_STEPS_1_0(res_struct->cfg_pi_floop_steps_1_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_1A_CFG_PI_FLOOP_STEPS_1_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_16(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_16_CFG_PI_EXT_DAC_23_16(res_struct->cfg_pi_ext_dac_23_16[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_16_CFG_PI_EXT_DAC_23_16);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_15(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_15_CFG_PI_EXT_DAC_15_8(res_struct->cfg_pi_ext_dac_15_8[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_15_CFG_PI_EXT_DAC_15_8);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_26(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_26_CFG_ISCAN_EXT_DAC_7_0(res_struct->cfg_iscan_ext_dac_7_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_26_CFG_ISCAN_EXT_DAC_7_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_42(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_42_CFG_CDR_KF_GEN1_2_0(res_struct->cfg_cdr_kf_gen1_2_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_42_CFG_CDR_KF_GEN1_2_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0F(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0F_R_CDR_M_GEN1_7_0(res_struct->r_cdr_m_gen1_7_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0F_R_CDR_M_GEN1_7_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_24(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_24_CFG_PI_BW_GEN1_3_0(res_struct->cfg_pi_bw_gen1_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_24_CFG_PI_BW_GEN1_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_14(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_14_CFG_PI_EXT_DAC_7_0(res_struct->cfg_pi_ext_dac_7_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_14_CFG_PI_EXT_DAC_7_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_1A(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_1A_CFG_PI_STEPS(res_struct->cfg_pi_steps[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_1A_CFG_PI_STEPS);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_3A(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_3A_CFG_MP_MAX_3_0(res_struct->cfg_mp_max_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_3A_CFG_MP_MAX_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_31(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_31_CFG_RSTN_DFEDIG(res_struct->cfg_rstn_dfedig[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_31_CFG_RSTN_DFEDIG);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_48(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_48_CFG_ALOS_THR_3_0(res_struct->cfg_alos_thr_3_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_48_CFG_ALOS_THR_3_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_36(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_36_CFG_PREDRV_SLEWRATE_1_0(res_struct->cfg_predrv_slewrate_1_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_36_CFG_PREDRV_SLEWRATE_1_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_32(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_32_CFG_ITX_IPCML_BASE_1_0(res_struct->cfg_itx_ipcml_base_1_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_32_CFG_ITX_IPCML_BASE_1_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_37(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_37_CFG_IP_PRE_BASE_1_0(res_struct->cfg_ip_pre_base_1_0[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_37_CFG_IP_PRE_BASE_1_0);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_41(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_41_CFG_LANE_RESERVE_15_8(res_struct->cfg_lane_reserve_15_8[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_41_CFG_LANE_RESERVE_15_8);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_9E(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_9E_R_EN_AUTO_CDR_RSTN(res_struct->r_en_auto_cdr_rstn[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_9E_R_EN_AUTO_CDR_RSTN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0C(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0C_CFG_OSCAL_AFE(res_struct->cfg_oscal_afe[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_0C_CFG_PD_OSDAC_AFE(res_struct->cfg_pd_osdac_afe[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0C_CFG_OSCAL_AFE |
        VTSS_M_SD10G_LANE_TARGET_LANE_0C_CFG_PD_OSDAC_AFE);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0B(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0B_CFG_RESETB_OSCAL_AFE(res_struct->cfg_resetb_oscal_afe[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0B_CFG_RESETB_OSCAL_AFE);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0B(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0B_CFG_RESETB_OSCAL_AFE(res_struct->cfg_resetb_oscal_afe[1]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0B_CFG_RESETB_OSCAL_AFE);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_83(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_83_R_TX_POL_INV(res_struct->r_tx_pol_inv[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_83_R_RX_POL_INV(res_struct->r_rx_pol_inv[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_83_R_TX_POL_INV |
        VTSS_M_SD10G_LANE_TARGET_LANE_83_R_RX_POL_INV);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_06(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_06_CFG_RX2TX_LP_EN(res_struct->cfg_rx2tx_lp_en[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_06_CFG_TX2RX_LP_EN(res_struct->cfg_tx2rx_lp_en[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_06_CFG_RX2TX_LP_EN |
        VTSS_M_SD10G_LANE_TARGET_LANE_06_CFG_TX2RX_LP_EN);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_0E(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_0E_CFG_RXLB_EN(res_struct->cfg_rxlb_en[0]) |
        VTSS_F_SD10G_LANE_TARGET_LANE_0E_CFG_TXLB_EN(res_struct->cfg_txlb_en[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_0E_CFG_RXLB_EN |
        VTSS_M_SD10G_LANE_TARGET_LANE_0E_CFG_TXLB_EN);

    REG_WRM(VTSS_SD_LANE_TARGET_SD_LANE_CFG(sd_lane_tgt),
                VTSS_F_SD_LANE_TARGET_SD_LANE_CFG_MACRO_RST(0),
                VTSS_M_SD_LANE_TARGET_SD_LANE_CFG_MACRO_RST);

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_50(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_50_CFG_SSC_RESETB(1),
                VTSS_M_SD10G_LANE_TARGET_LANE_50_CFG_SSC_RESETB);

    VTSS_MSLEEP(3);

    REG_RD(VTSS_SD_LANE_TARGET_SD_LANE_STAT(sd_lane_tgt), &value);
    value = VTSS_X_SD_LANE_TARGET_SD_LANE_STAT_PMA_RST_DONE(value);
    value = (value > 0) ? 1 : 0;
    if(value != 0x1) {
        VTSS_E("The expected value for sd_lane_stat pma_rst_done was 0x1 but is 0x%x\n", value);
        rc = VTSS_RC_ERROR;
    } else {
        VTSS_D("Note: The value of sd_lane_stat pma_rst_done was 0x%x\n", value);
    }

    REG_WRM(VTSS_SD10G_LANE_TARGET_LANE_34(sd_tgt),
                VTSS_F_SD10G_LANE_TARGET_LANE_34_CFG_PD_SQ(res_struct->cfg_pd_sq[0]),
                VTSS_M_SD10G_LANE_TARGET_LANE_34_CFG_PD_SQ);


  return rc;
}

/* This data is extracted from the MESA demo application - NPI port */
static vtss_sd10g28_setup_struct_t sdconf = {
	.cmu_sel = {0x1},
	.cfg_lane_reserve_7_0 = {0x40},
	.cfg_txrate_1_0 = {0x3},
	.cfg_rxrate_1_0 = {0x3},
	.cfg_cdrck_en = {0x1},
	.cfg_dfe_pd = {0x1},
	.cfg_erramp_pd = {0x1},
	.cfg_pi_en = {0x1},
	.cfg_summer_en = {0x1},
	.cfg_rx_reg_pu = {0x1},
	.cfg_en_main = {0x1},
	.cfg_tap_main = {0x1},
	.cfg_vga_ctrl_3_0 = {0x5},
	.cfg_vga_cp_2_0 = { 0x0 },
	.cfg_eq_res_3_0 = {0xa},
	.cfg_eqR_byp = {0x1},
	.cfg_eqC_force_3_0 = {0x8},
	.cfg_sum_setcm_en = {0x1},
	.cfg_itx_ipdriver_base_2_0 = {0x3},
	.cfg_ibias_tune_reserve_5_0 = {0x30},
	.cfg_dis_2ndOrder = {0x1},
	.cfg_pi_ext_dac_23_16 = {0x20},
	.cfg_iscan_ext_dac_7_0 = {0x89},
	.cfg_cdr_kf_gen1_2_0 = {0x1},
	.cfg_cdr_kf_gen2_2_0 = {0x1},
	.cfg_cdr_kf_gen3_2_0 = {0x1},
	.cfg_cdr_kf_gen4_2_0 = {0x1},
	.r_cdr_m_gen1_7_0 = {0x4},
	.cfg_pi_bw_gen1_3_0 = {0x9},
	.cfg_pi_bw_gen2 = {0x9},
	.cfg_pi_bw_gen3 = {0x9},
	.cfg_pi_bw_gen4 = {0x9},
	.cfg_pi_ext_dac_7_0 = {0x3},
	.cfg_mp_max_3_0 = {0x1},
	.cfg_alos_thr_3_0 = {0x3},
	.cfg_predrv_slewrate_1_0 = {0x3},
	.r_cdr_m_gen2_7_0 = {0x2},
	.r_cdr_m_gen3_7_0 = {0x2},
	.r_cdr_m_gen4_7_0 = {0x2},
	.cfg_oscal_afe = {0x1},
	.cfg_resetb_oscal_afe = {0x0, 0x1},
	.cfg_McntMaxVal_4_0 = {0xf},
	.cfg_ncntMaxVal_7_0 = {0x20},
	.cfg_ncntMaxVal_10_8 = {0x6},
	.cfg_ssc_en = {0x1},
	.r_rx_pol_inv = {0x1},
};

void fireant_serdes_port_init(int port,
			      u32 mac_type,
			      u32 serdes_type,
			      u32 serdes_idx)
{
	debug("Initializing port %d, serdes %d # %d\n",
	      port, serdes_type, serdes_idx);
	vtss_ant_sd10g28_reg_cfg(&sdconf, port, serdes_type, serdes_idx);
}

void fireant_serdes_cmu_init(void)
{
	int i;
	debug("%s: Init\n", __FUNCTION__);
	for(i = 0; i < 14; i++) {
		debug("%s: Init CMU %d\n", __FUNCTION__, i);
		vtss_ant_sd10g28_cmu_reg_cfg(i);
	}
}
